### ISSUE TITLE
FOL matching algorithm failed cast

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#100]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 13:37:22_

trying to apply automatic robinsion atp on the tape proof result in a failing cast in the fol matching algorithm. Can it be that the types of terms in hol is incorrect with regard to lambda?

java.lang.ClassCastException: at.logic.language.hol.HOLConst cannot be cast to at.logic.language.fol.FOLExpression
	at at.logic.algorithms.matching.fol.FOLMatchingAlgorithm$MatchingSubstitution.applyWithChangeDBIndices(FOLMatchingAlgorithm.scala:27)
	at at.logic.algorithms.matching.fol.FOLMatchingAlgorithm$MatchingSubstitution.applyWithChangeDBIndices(FOLMatchingAlgorithm.scala:32)
	at at.logic.algorithms.matching.fol.FOLMatchingAlgorithm$MatchingSubstitution.apply(FOLMatchingAlgorithm.scala:26)
	at at.logic.algorithms.matching.fol.FOLMatchingAlgorithm$MatchingSubstitution.apply(FOLMatchingAlgorithm.scala:22)
	at at.logic.algorithms.matching.fol.FOLMatchingAlgorithm$$anonfun$applySubToListOfPairs$1.apply(FOLMatchingAlgorithm.scala:45)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=100_

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 04:43:14_

when doing the following change in Function, many modules do not compile due to the same casting error:

the change is to return the term type as the return type in the function expression and not the type of the head variable

SimpleFOLParser should parse correctly an and  Time elapsed: 0.006 sec  \<<< ERROR!
  6 org.specs.runner.UserError: java.lang.ClassCastException: at.logic.language.fol.FOLFactory$$anon$1 cannot be cast to at.logic.language.fol.FOLTerm
  7         at at.logic.language.fol.FOLExpression$$anonfun$toString$1.apply(fol.scala:29)
  8         at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:123)
  9         at scala.collection.immutable.List.foldLeft(List.scala:45)
 10         at at.logic.language.fol.FOLExpression$class.toString(fol.scala:29)
 11         at at.logic.language.fol.FOLFactory$$anon$2.toString(fol.scala:265)

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 09:04:48_

the problem is that in the fol substitution in the matching algorithm, we try to apply the substitution to the two components of an App, casted as fol expressions. But the a fol expression represented as an App is never made from an application of two fol expressions (as one must be of function type which is impossible). The solution should be to match on all possible fol expressions and not on var, app and abs

**Owner:** cdunchev

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 09:08:20_

an example that failed:

list of terms: List((n_0,+(+(x_{2}, x_{4}), f(+(x_{1}, x_{0})))))
sub: Map(k_0 -> x_{3})

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 10:03:58_

fails also on:

list of terms: List((x_{1},x_{18}), (x_{0},∩(x_{17}, x_{15})))
sub: Map(x_{2} -> ∩(x_{17}, x_{16}))

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on January 07, 2011 05:58:02_

The variables in the second FOLExpression should be considered as constants when matching algorithm is applied

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on January 07, 2011 07:41:12_

Unfortunately, we can not avoid using the MatchingSubstitution in the FOLMatchingAlgorithm. The reason is that we can not prevent certain substitutions suring the substitution. For example, imagine that we have a substitution \sigma={x<-a, y<-b} and we want to apply it on the term f(y,x) where x is a member of moduloVarList. Then, we have to prevent the substitution {x<-a}, but this is not possible without explicitly saying that !moduloVarList.contains(x) during the substitution.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 07, 2011 07:51:25_

can you create a new substitution with is a subset of the original one? would be it enough for the restricted vars?

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 10, 2011 04:00:26_

now it works

**Status:** Fixed

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 25, 2011 22:36:02_

**Status:** Verified
