### ISSUE TITLE
Prime Proof Test fails

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#111]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on February 07, 2011 14:19:49_

What steps will reproduce the problem? 1. compile whole project including integration tests

The test fails because of "org.specs.runner.UserError: java.lang.IllegalArgumentException: requirement failed". In the backtrace it seems there is some problem with using the structs:

        at scala.Predef$.require(Predef.scala:133)
        at at.logic.utils.ds.trees.Tree$class.$init$(trees.scala:24)
        at at.logic.utils.ds.trees.BinaryTree.<init>(trees.scala:54)
        at at.logic.transformations.ceres.struct.Times.<init>(Struct.scala:68)
        at at.logic.transformations.ceres.struct.StructCreators$.makeTimesJunction(Struct.scala:120)
        at at.logic.transformations.ceres.struct.StructCreators$.extract(Struct.scala:98)
        at at.logic.transformations.ceres.struct.StructCreators$.handleUnary(Struct.scala:108)
[...]
        at at.logic.transformations.ceres.struct.StructCreators$.extract(Struct.scala:77)
        at at.logic.integration_tests.PrimeProofTest$$anonfun$1$$anonfun$apply$17.apply(PrimeProofTest.scala:165)
        at at.logic.integration_tests.PrimeProofTest$$anonfun$1$$anonfun$apply$17.apply(PrimeProofTest.scala:158)
[...]

This probably happens because we change struct to be a Tree?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=111_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on February 09, 2011 07:40:38_

Attached Backtrace

**Attachment:** [at.logic.integration_tests.PrimeProofTest.txt](http://code.google.com/p/gapt/issues/detail?id=111#hc1)

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on February 09, 2011 07:55:48_

it seems indeed that the failure is because of us describing structs as trees.
The requirement is distincting trees from dags as follows: if the same leaf (according to pointers equality as far as I can see in Tree.scala) occurs twice in an acyclic graph on two different paths to the same node, then this acyclic graph does not describe a tree. If this requirement for trees is indeed ok, then it means that the extraction of the struct create such a behavior. I think the main question is if Structs are trees or connected dags. Representing as dags is more efficient as it is allowed to reuse components in subgraphs (having more out edges from the same node, which in trees is limited to one - remark - it might be better to define trees according to this requirement). If they should be implemented as dags and we would like to display them as trees I suggest we write a transformation on acyclic graphs into trees which just duplicate nodes. So, in short we need the following answers:
1) Bruno, are structs trees or dags?
2) if they are dags, how to display them as trees.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on February 14, 2011 02:43:53_

Just as with formulas, I think you can in principle define structs as both DAGs and Trees. If the proof we extract the Struct from is a Tree, then it makes sense that the extracted Struct is a tree.

One thing that causes Structs to fail to be trees is the fact that multiple instances of e.g. EmptyTimesJunction are identified (because the vertices they induce are pointers to a common instance of the singleton that represents the symbol for EmptyTimesJunction).

I propose to introduce a new class

abstract class ExpressionOccurrence(val expression: HOLExpression) extends Occurrence

and change FormulaOccurrence to

abstract class FormulaOccurrence(val formula: HOLFormula, val ancestors: List[FormulaOccurrence]) extends ExpressionOccurrence(formula)

and change Struct to

trait Struct extends Tree[ExpressionOccurrence]

This would solve the problem I have described above. Still, it is not clear to me if this is the only thing that prevents Structs from being trees.

What do you think?

**Cc:** shaolintl

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on February 14, 2011 03:29:49_

This solution is much better if we need to manipulate the structs. I think that if the aim is just to display them in ProofTool maybe using an algorithm that transform a dag to a tree might be more efficient. What do you think?

**Cc:** -shaolintl fraini

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on February 14, 2011 03:37:48_

That is true, but I wonder what it would mean to have "an algorithm that transforms a dag to a tree" in this context. What I mean is: The old definition of Struct is

trait Struct extends Tree[HOLExpression]

I write now e for the empty struct, and x for the product. If we have a struct like

e x e

then we have the empty struct twice as a leaf. If we represent the empty struct by a single HOLExpression object, then we don't have a tree but a dag. So if we leave Struct to extend Tree[HOLExpression], we either have to change the notion of equality for HOLExpression, or introduce many "empty struct" symbols, to obtain a tree instead of a dag. It seems that both options are not desirable, and hence the definition of Struct should be changed anyways. Do you see an alternative to introducing ExpressionOccurrences to get a suitable definition of Struct?

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on February 14, 2011 04:18:39_

i thought maybe struct can extend dag and be used as a dag and only for the purpose of displaying it we will use an algorithm that takes a dag and duplicate all non-tree nodes. I am not sure it is so easy as if we want to duplicate we must have a way to create elements of the vertex of the dag. This might be done as you suggest so given a DAG[T] the resulted tree will contain Tree[Occurrence[T]] or something like that. It could be very easily done if we would have copy constructors for T and then in the algorithm we would call new T with Occurrence where occurrence just make sure the equality is pointer equality. But I am not sure it is possible in Scala. Anyway, your solution with occurrences sounds good to me as well. The only drawback with this solution is that the struct object itself is less efficient as it is displayed already as a tree.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on April 08, 2011 01:46:36_

In rev 661, it is implemented similar to what Tomer suggested: there is now a function

structToExpressionTree(s: Struct) : Tree[HOLExpression]

that takes a Struct (which is, by the case class semantics of scala, a DAG) and returns a Tree[HOLExpression] that represents the Struct.

**Status:** Fixed

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 18, 2011 08:57:27_

These issues are so old that I will assume that they have been already verified, even though their status still says otherwise...

In the future, remember: when you finish an issue, set its status to "fixed". From time to time, I will check the list of fixed issues, to verify that they are indeed fixed...

**Status:** Verified
