### ISSUE TITLE
Unification code does not compile

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#121]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on May 20, 2011 17:28:14_

When trying to compile GAPT, I get:

[INFO] ------------------------------------------------------------------------
[INFO] Building Unification algorithms
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /tmp/gapt-read-only/source/algorithms/unification/src/main/resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Nothing to compile - all classes are up to date
[INFO] [scala:compile {execution: default}]
[INFO] Checking for multiple versions of scala
[INFO] includes = [**/*.scala,**/*.java,]
[INFO] excludes = []
[INFO] /tmp/gapt-read-only/source/algorithms/unification/src/main/scala:-1: info: compiling
[INFO] Compiling 6 source files to /tmp/gapt-read-only/source/algorithms/unification/target/classes at 1305905023956
[INFO] java.lang.reflect.InvocationTargetException
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:597)
[INFO]  at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
[INFO]  at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: java.lang.Error: ch.epfl.lamp.fjbg.JCode$OffsetTooBigException: offset too big to fit in 16 bits: 176688
[INFO]  at ch.epfl.lamp.fjbg.JFieldOrMethod.writeTo(JFieldOrMethod.java:114)
[INFO]  at ch.epfl.lamp.fjbg.JClass.writeTo(JClass.java:315)
[INFO]  at scala.tools.nsc.backend.jvm.GenJVM$BytecodeGenerator.emitClass(GenJVM.scala:141)
[INFO]  at scala.tools.nsc.backend.jvm.GenJVM$BytecodeGenerator.genClass(GenJVM.scala:262)
[INFO]  at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase.apply(GenJVM.scala:56)
[INFO]  at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase$$anonfun$run$3.apply(GenJVM.scala:52)
[INFO]  at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase$$anonfun$run$3.apply(GenJVM.scala:52)
[INFO]  at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:89)
[INFO]  at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:89)
[INFO]  at scala.collection.Iterator$class.foreach(Iterator.scala:631)
[INFO]  at scala.collection.mutable.HashTable$$anon$1.foreach(HashTable.scala:161)
[INFO]  at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:194)
[INFO]  at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
[INFO]  at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:89)
[INFO]  at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase.run(GenJVM.scala:52)
[INFO]  at scala.tools.nsc.Global$Run.compileSources(Global.scala:741)
[INFO]  at scala.tools.nsc.Global$Run.compile(Global.scala:822)
[INFO]  at scala.tools.nsc.Main$.process(Main.scala:106)
[INFO]  at scala.tools.nsc.Main$.main(Main.scala:120)
[INFO]  at scala.tools.nsc.Main.main(Main.scala)
[INFO]  ... 6 more
[INFO] Caused by: ch.epfl.lamp.fjbg.JCode$OffsetTooBigException: offset too big to fit in 16 bits: 176688
[INFO]  at ch.epfl.lamp.fjbg.JCode.checkOffset16(JCode.java:896)
[INFO]  at ch.epfl.lamp.fjbg.JCode.patchAllOffset(JCode.java:975)
[INFO]  at ch.epfl.lamp.fjbg.JCode.freeze(JCode.java:95)
[INFO]  at ch.epfl.lamp.fjbg.JMethod.freeze(JMethod.java:81)
[INFO]  at ch.epfl.lamp.fjbg.JFieldOrMethod.writeTo(JFieldOrMethod.java:111)
[INFO]  ... 25 more
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240(Exit value: 240)

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4 minutes 6 seconds
[INFO] Finished at: Fri May 20 17:24:31 CEST 2011
[INFO] Final Memory: 43M/734M
[INFO] ------------------------------------------------------------------------

Can anyone confirm this?

Cvetan, this happens when compiling the unification code. Could you take a look at it? I think this error appears when a match { ... } statement is too long.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=121_

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 06:36:11_

Milestone Release 3.0 should contain all functionality for CERes Omega...

**Labels:** Milestone-Release3.0

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:27:13_

**Labels:** Component-TheoremProvers

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on August 22, 2011 04:28:31_

**Status:** Verified
