### ISSUE TITLE
exception in ivy parsing: unexpected expression (())

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#211]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on November 21, 2012 18:08:20_

Do the following using Geoff's prover9-solutions for the TPTP:

s_to_out \< ./SWC/SWC141+1/Prover9---1109a.THM-Ref.s > /tmp/test.out
scala> val r = loadProver9Proof( "/tmp/test.out" )
java.lang.Exception: Parsing Error: Unexpected expression (()) in parsing of a term.
        at at.logic.provers.prover9.ivy.IvyParser$.parse_term(Ivy.scala:707)
        at at.logic.provers.prover9.ivy.IvyParser$$anonfun$35.apply(Ivy.scala:675)
...

The parser should construct a resolution proof.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=211_

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on November 21, 2012 09:11:51_

to simplify testing I am attaching the test.out file here

**Attachment:** [test.out](http://code.google.com/p/gapt/issues/detail?id=211#hc1)

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 22, 2012 01:57:25_

The reason for this strange behaviour is that the proof constant the constant nil which has a different meaning in lisp (and therefore ivy). In case a term contains an empty list where a constant might be, we now create a constant named nil.

**Status:** Fixed
