### ISSUE TITLE
Robinson2LK throws exception on resolution proof imported from prover9

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#212]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on November 21, 2012 18:14:52_

Using Geoff's prover9-solution of the TPTP do the following:

s_to_out \< ./BOO/BOO003-2/Prover9---1109a.UNS-Ref.s > /tmp/test.out

scala> val r = loadProver9Proof( "/tmp/test.out" )
[...]

scala> val p = Robinson2LK( r )
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:274)
        at scala.None$.get(Option.scala:272)
        at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:108)
[..]

As far as I can see, the proof r looks still fine.

To simplify testing I am attaching test.out.

**Attachment:** [test.out](http://code.google.com/p/gapt/issues/detail?id=212)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=212_

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 21, 2012 12:01:13_

**Owner:** shaoli...@gmail.com  
**Cc:** -shaoli...@gmail.com stefan.hetzl  
**Blockedon:** gapt:213

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 21, 2012 12:05:30_

**Blockedon:** -gapt:213

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 21, 2012 13:59:34_

There is indeed a bug in the function. I apply recursively in order to get a ground LK proof but then I need to find the auxiliary formula in the upper LK proofs. 

The fix is to return the grounding substitution together with the LK proof and use it (instead of the partial curSub I am using now) in order to compute the ground auxiliary formulas in the upper LK proofs.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 22, 2012 13:31:32_

Hi Martin,

I changed it as written above and noticed that the two substitutions returned from the two subtrees (in para for example) bind the same variables to different terms. Looking closer on the proof it seems that clauses with shared variables are resolved and modulated together. So unless I made a bug in the debugging, can it be that no variants are taken when constructing the proof? I apologize if my question is trivial and there are variants but I prefer to ask before I spend more time on the problem.

anyway, I think there was a bug before and I commit the fix for that

I am still not sure how one can create a resolution proof where one resolve on clauses with shared variables when indeed two occurrences of the shared variable must be mapped to different terms.

In the example you attached I get:
sub1: v0 -> add(additive_identity, inverse(additive_identity))
v1 -> multiplicative_identity
sub2: v0 -> additive_identity
v1 -> inverse(additive_identity)

anyway, I have added an assertion in algorithms/resolution/robinson.scala that fails on this problem on the example you attach. If the problem is indeed in the resolution proof and you solve it, please remove this assertion, otherwise, if the problem is indeed in my code, please leave it and I will remove it.

**Owner:** Martin.R...@googlemail.com  
**Cc:** -Martin.R...@googlemail.com shaoli...@gmail.com

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 22, 2012 15:58:41_

I think the problem is rather the fact that resproofs are dags and lkproofs are trees, What do you think Martin?

without relevance to the substitutions, my algorithm cannot create the lk proof.
Do you know if you create a tree or a dag?

Anyway, I will do the transformation (dag -> tree) in the algorithm as well and then it should not be a problem

**Status:** Started  
**Owner:** shaoli...@gmail.com  
**Cc:** -shaoli...@gmail.com Martin.R...@googlemail.com

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 22, 2012 16:06:03_

I forgot I do create a tree in the transformation. So Martin, can you check if the variants are created properly?

**Status:** New  
**Owner:** Martin.R...@googlemail.com  
**Cc:** -Martin.R...@googlemail.com shaoli...@gmail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 22, 2012 23:39:36_

Hi Tomer, yes I have a bug in paramodoulation which i didn't manage to catch until now, i have class at 9 but afterwards ill go back to debugging.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 23, 2012 05:20:53_

if the problem is missing variants then it should occur in resolving steps as well.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 23, 2012 11:17:02_

I still couldn't narrow it down nicely. When you uncomment the prime1-0sk test in ./provers/prover9/src/test/scala/at/logic/provers/prover9/IvyTest.scala you get an exception during translation from Lisp's SExpressions to IvyResolution which means i'm quite sure i construct wrong paramodulation inferences alltogether.

What i suppose that happens there is that during a paramodulation inference, a literal gets lost and then a resolution inference is working on the wrong literal because the formulas to work on are indicated as positions into the clause expression. Since the instance formula is taken directly instead of being inferred, the inference might get constructed even though it is not sound.

Could you confirm that pure resolution proofs work fine, as that is what we ned for the paper, right?

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 23, 2012 12:01:59_

I dont know, I did not check many proofs but it seems to me the problem might not be only wrong literals but variants as well as the example shows the same variable being substituted with two different terms. Can you try creating the resolution proofs with variants? I.e. before each resolution/para on two clauses you apply the variant rule on each of these two clauses and apply the res/para to the variants.

It might be useless and I dont really understand whats going on with the translation you made but the output look suspicious in the example above.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 23, 2012 12:40:34_

Actually, I create the Para and Res steps without substitution since instantiation takes care of variable renaming - i'll surely try it, but to have this correctly done I must apply the correct renaming to the fresh variables to other parts of the proof(i'm still not 100% sure but as far as i encountered, prooftrans generates an instantiation before each Res/Para so i might also double the work). I'll report back tomorrow.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 23, 2012 12:47:53_

even though it seems to be a correct local step (inst the local variables before binary rules), when trying to compute a global substitution, I think that using the same clauses several times without renaming their variables results in a wrong (global) substitution. No?

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 24, 2012 16:21:32_

Status update for this one: i narrowed the break down to the following subproof (i put it into a pdf for easier reading and give the ivy proof inline):

(
(10 (input) (= (multiply v0 v1) (multiply v1 v0)) NIL)
(15 (input) (= (multiply (add v0 v1) v2) (add (multiply v0 v2) (multiply v1 v2))) NIL)
(100 (instantiate 10 ((v0 . (add v0 v1)) (v1 . v2))) (= (multiply (add v0 v1) v2) (multiply v2 (add v0 v1))) NIL)
(101 (paramod 100 (1) 15 (1)) (= (multiply v2 (add v0 v1)) (add (multiply v0 v2) (multiply v1 v2))) NIL)
)

As far as i see the substitution x \<- x+y is the reason, although the error here is a different one (and i don't understand Tomer's code that well). At least when the lower proof in the pdf is used, the translation works, but i still dont know if this is luck or something else.

I entered the proof by hand in our datastructures that we can be sure that the Ivy parser is not creating additional problems. The file algorithms/resolution/src/test/scala/at/logic/algorithms/resolution/ResolutionToLKTest.scala contains 3 new test cases (one of which creates the error), the other two work out. The proofs are constructed in the objects UNSproof, UNSproofFreshvars and UNSproofVariant in the beginning of the file.

**Attachment:** [proof.pdf UNSmini.ivy](http://code.google.com/p/gapt/issues/detail?id=212#hc13)

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 24, 2012 16:34:21_

One additional comment: as far as I see the original UNSproof is a derivation we want to handle. So basically we could seperate the task from parsing and Robinson2LK by writing a transformation which changes the problematic variables to fresh ones.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 26, 2012 15:03:07_

I reverted the "fix" from above. the subs are not idempotent and therefore  we must apply the right version of it at each step and not accumulate it.
it solves the UNSproof by Martin but still fails on the test.out by Stefan.

It seems that due to the non-idempotent of subs, no correct accumulation is possible.
i.e. if we compose s1,s2 and s3 where
s1 = {x->a}
s2 = {y->fx}
s3 = {x->fy}

we get just x->a, y->fa
although the ground sub should have been x->ffa, y->fa

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 26, 2012 15:30:16_

so to summarize, I dont see any option for an inductive algorithm for grounding the resolution proof using substitutions whose accumulation becomes cyclic.

Martin, would it be possible to use fresh variables when the variable does not occur in the problem? i.e. the first and second x would be z. I am not sure it is enough but it will solve the current problem we have.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 26, 2012 16:02:08_

Hi Tomer!

I think the easiest way to do this is by writing a method substitute: (ResolutionProof, Substitution) => ResolutionProof which applies the given substitution correctly to a proof. Now we can write a method unfold which applies substitute to both parent proofs and inserts fresh variables. Afterwards we will have unfolded the dag to a tree and should not have any cyclicity conditions anymore.

Alternatively i would propose a method purify which moves instantiations into the following rules. For a binary rule, we create a variant of both parents of the instantiation rule, where every variable in the domain of the instance substitution is assigned a fresh variable and the substitutions are changed accordingly. Then the substitutions can be merged into one and moved into the binary rule.
So
  
       (pi)            (rho)
    X ------        ---------- Y
        C               D
Inst  ---------     ----------
       C.sigma         D.tau
      -------------------------- BI
                 F

gets transformed into:

         (pi)            (rho)
       X ------        ---------- Y
            C               D
Variant  ---------     ----------   Variant
          C.sigma'         D.tau'
         -------------------------- BI
                 F.theta


where sigma' and tau' are the renamings to fresh variables and theta is the merged substitution of sigma and tau, but with domain the introduced fresh variables.

In any case I think these methods should be seperate from the actual parsing and not merged into it. There is still the matching of clauses to formulas on my todo list and i only have ~5 hours of holes from 8am to 9pm between appointments in the next 3 days, so if someone would like to take over implementing one of the two approaches, it would lift a heavy burden from me.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 27, 2012 02:09:41_

**Cc:** mrukh...@gmail.com

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 27, 2012 05:15:55_

Hi Martin,

I agree it should be separated from parsing but also from the transformation to LK.
I like more the second way. Doing a post processing to the proof to make sure the substitutions behave corrrectly and only then calling the robinson2lk.

Regarding helping with this code, I am afraid I wont be able. except my own duties I also have to take care of my daughter as Irina is going to defend her thesis soon and needs to prepare.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 28, 2012 14:10:18_

Hi Tomer!

So if anyone else likes to volunteer, please just tell me. Otherwise i'll start implementing a function for this on the weekend.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 16, 2012 13:50:56_

Hi all!

I now implemented the instance removal algorithm described above, but the problem still persists although the UNSmini subproof i posted earlier is correctly translated now.

**Attachment:** [UNSnoinst.pdf UNSnoinst.svg](http://code.google.com/p/gapt/issues/detail?id=212#hc21)

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 17, 2012 02:35:34_

There was some problem with generating frsh variables which is (hot-)fixed now. The problem persists though :(

**Attachment:** [UNSnoinst.dot UNSnoinst.pdf UNSnoinst.svg](http://code.google.com/p/gapt/issues/detail?id=212#hc22)

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 18, 2012 05:34:20_

Hi all!

Mikheil just added a view for RobinsonResolutionProofs in prooftool, so we can look at them directly. If the instantiation is empty, we skip it entirely which prevents superfluous variant rules.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 19, 2012 14:53:03_

Hi Martin,
why do you rename some variables as v.. and some as x..?

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 19, 2012 15:05:12_

Hi Martin,
If you look on the proof in prooftool, you see that you dont apply a variant on some initial clauses which cause the cyclic variable dependency again.
Attached is a print screen.

**Attachment:** [error.tiff](http://code.google.com/p/gapt/issues/detail?id=212#hc25)

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 20, 2012 01:48:52_

Hi Tomer!

vN are variables introduced by the proof conversion, x_N are fresh variables generated by instantiation elimination. The reason that v2 is not assigned a fresh variable is that v2 is not part of the substitution. I am just writing some cli code to show you what i mean.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 26, 2012 00:22:48_

seems the problem is closed. The fix was the application of substitution from leaves to root. Since the proof is not regular, this is the only way to apply a substitution:by applying each sub to the upper sequents and not try to accumulate it (which is impossible)

**Status:** Fixed
