### ISSUE TITLE
Exception in Robinson2LK (PCNF)

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#221]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 10, 2013 13:05:56_

In the CLI do:

loadProver9LKProof( "../testing/prover9-TSTP/ALG/ALG012-1/Prover9---1109a.UNS-Ref.s.out" )

A proof should be loaded, instead an exception is thrown.

Similar exceptions are thrown at a number of other examples in the ALG-part of the prover9-TSTP, e.g. ALG431-1 They seem to have a common cause: often the reflexivity axiom is mentioned, maybe it is related to that...

_Original issue: http://code.google.com/p/gapt/issues/detail?id=221_

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 10, 2013 05:08:52_

A similar (the same ?) problem appears _very_ often in the PUZ-category: a clause cannot be found in the CNF of the formula. This appears for example in PUZ047-1, PUZ003-1, PUZ063-1, PUZ026-1, PUZ007-1, PUZ008-3,...

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 10, 2013 05:11:03_

very possible that is is because of reflexivity as we dont have any such axiom in LK.

I will check that over the weekend.

**Owner:** shaoli...@gmail.com  
**Cc:** -shaoli...@gmail.com stefan.hetzl

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 10, 2013 05:16:24_

Yes, reflexivity seems to be the issue in the examples from the ALG-category. But (most of) the examples in the PUZ-category mentioned above do not even contain equality.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 10, 2013 07:20:29_

Yes, reflexivity could cause a problem. I use it in order to simulate the flip rule, so it is not contained in the original problem.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 11, 2013 02:49:44_

Fixed the reflexivity issue but there are still problems with the parsing:

End-sequent is skolemized.
java.lang.IllegalArgumentException: Clause [ :- =(f(v0, f(v1, v2)), f(f(v0, v1), v2))] is not reflexivity and not contained in CNF(-s) [
 :- d2(a3);
 :- =(f(v2, f(v0, v1)), f(f(v2, v0), v1));
 :- c(v0), d1(v0);
 :- c(v0), d2(v0);
 :- c(v0), d1(v0), d2(v0);
 :- c(f(v1, v0)), d1(v1), d1(v0);
 :- c(f(v1, v0)), d2(v1), d2(v0);
 :- d2(f(v1, v0)), d1(f(v1, v0)), c(v1), c(v0)
]

**Owner:** Martin.R...@googlemail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 11, 2013 03:03:07_

yes, this is a problem of the variable renaming -- i think it's still different from the one ivy does. in the worst case i will do something similar that Robinson2LK does: bring the formulas of the end-sequent into clause form and find matching of formula to clause variables for each clause. Then replace introduction inference by a variant which does the right thing. (I avoided this till now since it sounds prone to errors)

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 11, 2013 05:21:39_

check containment of a \<- cnf^-(s) up to variable renaming

**Owner:** shaoli...@gmail.com

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 11, 2013 10:24:15_

I think I fixed the renaming but now I get that I need to rename constants as well ?! Martin?

Java.lang.IllegalArgumentException: Clause [ :- d1(a2)] is not reflexivity and not contained in CNF(-s) [
 :- d2(a3);
 :- =(f(v2, f(v0, v1)), f(f(v2, v0), v1));
c(v0), d1(v0) :- ;
c(v0), d2(v0) :- ;
 :- c(v0), d1(v0), d2(v0);
d1(v1), d1(v0) :- c(f(v1, v0));
d2(v1), d2(v0) :- c(f(v1, v0));
c(v1), c(v0) :- d2(f(v1, v0)), d1(f(v1, v0))
]
        at at.logic.algorithms.resolution.PCNF$.apply(PCNF.scala:55)

**Owner:** Martin.R...@googlemail.com  
**Cc:** -Martin.R...@googlemail.com shaoli...@gmail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 11, 2013 14:01:26_

Ok, so in the original tptp file it's also definitely d1(a2). I will report when i find out more...

**Attachment:** [ALG012-1.p](http://code.google.com/p/gapt/issues/detail?id=221#hc9)

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 11, 2013 14:22:18_

It's a bug in prooftrans, the clause is just put into the xml comments:

\<proof number="1" length="52" max_count="24">

\<comments><![CDATA[
% Proof 1 at 4.71 (+ 0.07) seconds.
% Length of proof is 53.
% Level of proof is 16.
% Maximum clause weight is 24.000.
% Given clauses 277.
2 d1(a2) # label(_14478) # label(_14482).  [assumption].
]]></comments>

  \<clause id="3" type="assumption">
    \<literal><![CDATA[
      d2(a3)
    ]]></literal>

i can try to remove the xml transformation... it seems it's just introducing more bugs than anything else.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 11, 2013 16:01:43_

Ok commit r1404 parses the formula now directly, but ALG012-1 example is now stuck in an endless loop within Robinson2LK and the goat example fails:

val p = loadProver9LKProof( "provers/prover9/src/test/resources/PUZ047+1.out")

gives the following output:

WARNING: trying to substitute for a bound variable, ignoring!
WARNING: trying to substitute for a bound variable, ignoring!
WARNING: trying to substitute for a bound variable, ignoring!
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:274)
	at scala.None$.get(Option.scala:272)
	at at.logic.algorithms.resolution.PCNF$.PCNFp(PCNF.scala:128)
	at at.logic.algorithms.resolution.PCNF$.PCNFp(PCNF.scala:132)
	at at.logic.algorithms.resolution.PCNF$.PCNFp(PCNF.scala:132)
	at at.logic.algorithms.resolution.PCNF$.PCNFp(PCNF.scala:132)
	at at.logic.algorithms.resolution.PCNF$.apply(PCNF.scala:41)
	at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:51)
	at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:126)
	at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:87)
	at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:86)
	at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:86)
	at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:86)
	at at.logic.algorithms.resolution.RobinsonToLK$.apply(robinson.scala:28)
	at at.logic.cli.GAPScalaInteractiveShellLibrary.Robinson2LK$.apply(GAPScalaInteractiveShellLibrary.scala:538)
	at at.logic.cli.GAPScalaInteractiveShellLibrary.loadProver9LKProof$.apply(GAPScalaInteractiveShellLibrary.scala:564)

you can check against the old implementation by calling:

val p = loadProver9LKProof( "provers/prover9/src/test/resources/PUZ047+1.out",false)

but it gives the same error.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 11, 2013 23:40:45_

Thanks, it is proabably an error in my implementation yesterday, I have to apply substitutions and the terms again have shared variables. I will check it today.

**Owner:** shaoli...@gmail.com  
**Cc:** -shaoli...@gmail.com Martin.R...@googlemail.com

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 12, 2013 12:36:48_

indeed, applying the sub to the formulas was not enough as the variables could be quantified. I apply the sub to the resulted proof now.

The problem with constants still persists:

java.lang.IllegalArgumentException: Clause [ :- d1(a2)] is not reflexivity and not contained in CNF(-s) [
 :- d2(a3);
 :- =(f(A, f(B, C)), f(f(A, B), C));
c(A), d1(A) :- ;
c(A), d2(A) :- ;
 :- c(A), d1(A), d2(A);
d1(A), d1(B) :- c(f(A, B));
d2(A), d2(B) :- c(f(A, B));
c(A), c(B) :- d2(f(A, B)), d1(f(A, B))
]
	at at.logic.algorithms.resolution.PCNF$.apply(PCNF.scala:68)

**Owner:** Martin.R...@googlemail.com  
**Cc:** -Martin.R...@googlemail.com shaoli...@gmail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 12, 2013 16:02:47_

Hi Tomer!

My apologies, when i added the choice between old and new implementation i made stupid error. Now it will also extract the missing clause, Robinson2LK somehow loops (it seems to find all clause - formula correspondences).

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 13, 2013 06:49:46_

It is probably because of the addition of variable renaming. It is too complex and I think I will drop it. I will try in parallel to fix the bug but I am not sure I will have the time. I will rollback to a safe version.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 13, 2013 11:28:36_

I am using now your "skolemization" procedure in order to avoid variable renaming. I think it is enough for the computation of expansion trees as the formulas not used in the refutation are not interesting anyway. I think this solves this bug.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 14, 2013 05:55:03_

I returned the variablesRenaming as the solution proposed above makes the expansion trees trivial. Martin, the problem right now is that some input is in CNF and you need to universally close it. Is it OK for you?

**Comment by newca12** [comment]
_From [lambda.x...@gmail.com](https://code.google.com/u/103054511164786171111/) on January 14, 2013 06:43:34_

Hi Tomer, there is already a function which does this in https://code.google.com/p/gapt/source/browse/trunk/source/cli/src/main/scala/at/logic/cli/GAPScalaInteractiveShellLibrary.scala : loadProver9LKProof.univclosure -- it is also called before passing a formula to Robinson2LK (see the code of loadProver9LKProof's apply method above).

I'm sorry i'm not participating in the discussion but i'm completely confused by the discussion at the moment.

**Comment by newca12** [comment]
_From [lambda.x...@gmail.com](https://code.google.com/u/103054511164786171111/) on January 14, 2013 06:45:21_

And Tomer: our skolemization introduces diefferent skolem symbols than prover9, so we cannot use it as a replacement. We can only extract the CNF from the proof instead of the original formula. (see also loadProver9LKProof.apply )

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 14, 2013 06:50:25_

Hi Martin,

sorry for the confusion. I thought of solving the variable renaming problem by just always computing the endsequent from the proof using your function. Stefan enlightened me that this destroys the structure of the trees and renders them not so interesting.
So we dropped this idea.

I went back on computing the variable renamings inside the PCNF. The problem is that I have to apply it to the PCNF in order to get a valid LK proof. The problem then is that the endsequent is not s but s\circ\theta for some unknown \theta (as each PCNF affects theta). This should not be a problem since s should be a universally closed sequent on all variables which get instantiated. This is not the case when you load an endsequent which is already in cnf.

So what we need now is that when you load an endsequent, if it is in CNF then you apply your universal closure method on it before passing it to me.

**Comment by newca12** [comment]
_From [lambda.x...@gmail.com](https://code.google.com/u/103054511164786171111/) on January 14, 2013 07:10:32_

But the CNF extraction is only correct if the clauses are universally closed - therefore i already perform the closure in loadProver9LKProof.apply : 


val clauses = fclauses.map( c => univclosure(fol.Or(c.neg.map(f => fol.Neg(f.asInstanceOf[FOLFormula])) ++ c.pos.map(f => f.asInstanceOf[FOLFormula])))  )

at line 574

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 14, 2013 07:22:28_

do you also perform it if you read a skolemized end sequent which is in CNF?

**Comment by newca12** [comment]
_From [lambda.x...@gmail.com](https://code.google.com/u/103054511164786171111/) on January 14, 2013 07:32:20_

no, i will do that

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 14, 2013 07:54:26_

looks good, thanks

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 12, 2013 07:49:06_

Since the file now loads, I assume the problem to be fixed.

**Status:** Fixed
