### ISSUE TITLE
error when parsing ivy proofs: may contain exactly one proof object

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#230]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 15, 2013 17:06:06_

repeats on many cases in ALG and REL, for example on:

/home/shaolin/Documents/gapt/testing/prover9-TSTP/REL/REL048-1
/Prover9---1109a.UNS-Ref.s.out

java.lang.IllegalArgumentException: requirement failed: An ivy proof may contain only exactly one proof object!
        at scala.Predef$.require(Predef.scala:214)
        at at.logic.provers.prover9.ivy.IvyParser$.apply_(Ivy.scala:48)
        at at.logic.provers.prover9.ivy.IvyParser$.apply(Ivy.scala:41)
        at at.logic.provers.prover9.Prover9$.parse_prover9(Prover9.scala:197)
        at at.logic.cli.GAPScalaInteractiveShellLibrary.loadProver9LKProof$.apply(GAPScalaInteractiveShellLibrary.scala:558)
        at $line29.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$testProver9Import$$anonfun$apply$2$$anonfun$1.apply(<console>:82)
        at $line29.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$testProver9Import$$anonfun$apply$2$$anonfun$1.apply(<console>:82)
        at $line29.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$testProver9Import$$anon$1.run(<console>:117)
        at java.lang.Thread.run(Thread.java:722) What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=230_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 18, 2013 09:19:22_

This issue was closed by revision r1424 .

**Status:** Fixed

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 18, 2013 09:28:57_

Remark: still doesn't compile due to issue #231
