### ISSUE TITLE
Ivy paramodulation do not detect demodulation

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#231]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 18, 2013 18:28:28_

try:

scala> val p = loadProver9LKProof("/home/marty/Projects/gapt/testing/prover9-TSTP/KLE/KLE144+2/Prover9---1109a.THM-Ref.s.out")

Debug: processing inference 54D
Debug: found occurrence of equation: =(addition(v0, addition(v1, v1)), addition(v1, addition(v0, v1)))[10071] at pos List(2)
Debug: found occurrence of target formula:=(addition(v0, addition(v1, addition(v0, v1))), addition(v1, v0))[10070] at pos List(1, 2)
Debug: true
Debug: remaining position: List(1, 2) full position List(1, 2)
Debug: replace: addition(v0, addition(v1, v1)) by addition(v1, addition(v0, v1)) in =(addition(v0, addition(v1, addition(v0, v1))), addition(v1, v0))
java.lang.Exception: Error in parsing replacement: (sub)term addition(v1, addition(v0, v1)) is not the expected term addition(v0, addition(v1, v1))
	at at.logic.provers.prover9.ivy.IvyParser$.replaceTerm_by_in_at(Ivy.scala:610)
	at at.logic.provers.prover9.ivy.IvyParser$.replaceTerm_by_in_at(Ivy.scala:605)
	at at.logic.provers.prover9.ivy.IvyParser$.replaceTerm_by_in_at(Ivy.scala:601)
	at at.logic.provers.prover9.ivy.IvyParser$.parse_step(Ivy.scala:298)
	at at.logic.provers.prover9.ivy.IvyParser$.parse(Ivy.scala:96)
	at at.logic.provers.prover9.ivy.IvyParser$.parse(Ivy.scala:81)
	at at.logic.provers.prover9.ivy.IvyParser$.apply_(Ivy.scala:51)
	at at.logic.provers.prover9.ivy.IvyParser$.apply(Ivy.scala:42)
	at at.logic.provers.prover9.Prover9$.parse_prover9(Prover9.scala:197)

The problem is that given the equation s=t the parser expects paramodulation to replace s by t. Sometimes this is also translated as demodulation where t should be replaced by s. This case is not handled (and therefore the error in the positions parsing).

P.S. this issue is mainly for documentation reasons

_Original issue: http://code.google.com/p/gapt/issues/detail?id=231_

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 19, 2013 02:04:46_

This seems closely related to issue #228 , should we merge the two?

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2013 11:25:42_

Yes, you are right.

**Status:** Duplicate  
**Mergedinto:** 228
