### ISSUE TITLE
Skolemization on LinearExampleProof fails

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#234]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on February 27, 2013 19:47:47_

In the CLI, enter:
skolemize( LinearExampleProof( 4 ))

which produces the exception:
java.lang.Exception: String conversion of FOL expression failed: ∀x.(P(x)⊃P(s(x)))
        at at.logic.language.fol.FOLExpression$class.toString(fol.scala:68)
        at at.logic.language.fol.FOLFactory$$anon$2.toString(fol.scala:427)
        at java.lang.String.valueOf(String.java:2838)
[...]

This proof does not contain a strong quantifier.

This would make another good integration test once it is fixed.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=234_

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on May 03, 2013 04:58:07_

Hi,

after some tests I found the cause of this problem. So, LinearExampleProof(4) generates a first-order proof with first-order formulas. The method skolemize() is implemented initially for HOL and FOL (there's some distinction in the code on first and higher order formulas when creating a skolem term), but all the parameters are passed as HOLFormula (in particular in the method sk()). If you notice, when treating a weakly quantified formula, this sk() method just keeps the quantifier (lines 466 and 488 of skolemization.scala). I guess this is when the FOLFormula is cast into a HOLFormula. This will not break the skolemization, of course... The process continues until the proof is skolemized with no problem. But then scala wants to print this proof and calls toString() from fol.scala. If you observe the comment on line 65, the code breaks if this is a HOLFormula. This is where the exception is thrown. In order to make this clearer, I modified the code such that it prints "#" instead of throwing an exception. After applying skolemization there was # in the place of all quantified formulas:

res11: at.logic.calculi.lk.base.LKProof = ContractionLeftRuleType(P(0),  #  :- P(s(s(s(s(0))))), ForallLeftRuleType(P(0),  # ,  #  :- P(s(s(s(s(0))))), ImpLeftRuleType(P(0),  # , (P(0)⊃P(s(0))) :- P(s(s(s(s(0))))), InitialRuleType(P(0) :- P(0)), ContractionLeftRuleType(P(s(0)),  #  :- P(s(s(s(s(0))))), ForallLeftRuleType(P(s(0)),  # ,  #  :- P(s(s(s(s(0))))), ImpLeftRuleType(P(s(0)),  # , (P(s(0))⊃P(s(s(0)))) :- P(s(s(s(s(0))))), InitialRuleType(P(s(0)) :- P(s(0))), ContractionLeftRuleType(P(s(s(0))),  #  :- P(s(s(s(s(0))))), ForallLeftRuleType(P(s(s(0))),  # ,  #  :- P(s(s(s(s(0))))), ImpLeftRuleType(P(s(s(0))),  # , (P(s(s(0)))⊃P(s(s(s(0))))) :- P(s(s(s(s(0))))), InitialRuleType(P(s(s(0))) :- P(s(s(0)))), ContractionLeftRuleType(P(s(s(s(0)))),  #  :- P(s(s(s(s(0))))), ForallLeftRuleTy...

Then I started making some tests with these formulas:

scala> val f = res11.root.antecedent(1)
f: at.logic.calculi.occurrences.FormulaOccurrence =  # [10169]

scala> val fhol = f.formula.asInstanceOf[HOLFormula]
fhol: at.logic.language.hol.HOLFormula =  # 

scala> val ffol = f.formula.asInstanceOf[FOLFormula]
ffol: at.logic.language.fol.FOLFormula =  # 

scala> val f_hol2fol = hol2fol(fhol)
f_hol2fol: at.logic.language.fol.FOLFormula = ∀x.(P(x)⊃P(s(x)))

So usual casting does not work, and I had to use the hol2fol() method. Of course, calling hol2fol before the toString() method from fol.scala is ugly and not an option. I am not sure what is the best way to fix this. We can of course check the type of the formula during skolemization and use the right quantifier, but this seems just a work around... and this would have to be done for every method that's supposed to work for HOL and FOL.
Can anyone explain to me what is the class relation between HOL and FOL, if any?

I thought about this a little, and I am not sure that relating these classes are the best option. This is because there are methods for FOL that do not work on HOLFormulas and vice-versa. But then, if these classes are not somehow related, every method that works for both would have to be implemented twice, which is also not nice. The best I could think is to have a parent class A from which HOL and FOL are subclasses... Then every method that should work for both is implemented for A and methods specific to each one are implemented for the correct class. 

What do you think?

Best,
Giselle

**Cc:** shaoli...@gmail.com fra...@gmail.com giselle....@gmail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on May 08, 2013 09:45:41_

**Blockedon:** gapt:238

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on April 18, 2014 07:59:38_

Solved in the new lambda-calculus.

**Status:** Fixed
