### ISSUE TITLE
Some prover9 proof cannot be translated to LK.

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#247]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on November 11, 2013 22:55:29_

* What steps will reproduce the problem?

tptp.in:
fof( to_prove, conjecture, ( ( ( ( ( ~'P'('0')) | ( ~( 'P'('s'('s'('a'))) => 'P'('s'('s'('s'('a')))) )) ) | ( ~( 'P'('a') => 'P'('s'('a')) )) ) | ( ( 'P'('s'('s'('s'('a')))) | ( ~'P'('s'('s'('a')))) ) & ( 'P'('s'('a')) | ( ~'P'('a')) ) ) ) | 'P'('s'('s'('s'('s'('0'))))) )).

tptp_to_ladr \< tptp.in > p9.in
prover9 \< p9.in > p9.out

Then, in the gapt CLI:

loadProver9LKProof( "p9.out" )

* What is the expected output? What do you see instead?

A proof imported from Prover9. Instead, the following exception is thrown:

java.lang.IllegalArgumentException: clause:  :- ladr3(ladr1(ladr1(ladr0))), ladr3(ladr0) is not found in CNFs of ancestors: Set(ladr3(ladr1(ladr1(ladr1(ladr0)))) :- ) or Set( :- ladr3(ladr1(ladr1(ladr0))))
        at at.logic.algorithms.resolution.PCNF$.PCNFn(PCNF.scala:114)
        at at.logic.algorithms.resolution.PCNF$.PCNFn(PCNF.scala:109)
        at at.logic.algorithms.resolution.PCNF$.apply(PCNF.scala:54)
        at at.logic.algorithms.resolution.RobinsonToLK$$anonfun$apply$1.apply(robinson.scala:30)
        at at.logic.algorithms.resolution.RobinsonToLK$$anonfun$apply$1.apply(robinson.scala:30)
        at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:69)
[...]

Maybe weakening is missing? In my working copy, I'm using the following
which adds weakenings to a proof to "complete" a sequent. I of course lifted that code from introduceContractions :-)

  /**
  * introduce weakenings to recover the end-sequent (if a formula is not used in
  * the proof.)
  */
  def introduceWeakenings(resp: LKProof, s: FSequent): LKProof= {
    println(" *****************     introducing weakenings ****************** ")
    // for each formula F in s, count its occurrences in s and resp and apply weakenings on resp until we reach the same number
    val p1 = s.antecedent.toSet.foldLeft(resp)((p,f) =>
      ((1).to(s.antecedent.filter(_ == f).size - p.root.antecedent.filter(_.formula == f).size)).foldLeft(p)((q,n) =>
        WeakeningLeftRule(q,f) ))
    val p2 = s.succedent.toSet.foldLeft(p1)((p,f) =>
      ((1).to(s.succedent.filter(_ == f).size - p.root.succedent.filter(_.formula == f).size)).foldLeft(p)((q,n) =>
        WeakeningRightRule(q,f) ))
    println(" *****************   new end-sequent: " + p2.root + " ****************** ")
    p2
  }

Could someone in the know about the RobinsonToLK algorithm have a look at this? Thanks!

_Original issue: http://code.google.com/p/gapt/issues/detail?id=247_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 12, 2013 03:06:26_

Hi Daniel!

I'm looking into it - actually we should not need to weaken anything after the CNF transformation, so I'll have a look what goes wrong. I have a modified version of your input file attached which gives easier to read output.

**Attachment:** [daniel2.tptp daniel2.out](http://code.google.com/p/gapt/issues/detail?id=247#hc1)

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 12, 2013 06:18:58_

I identified the problem, but i'm not sure how to fix it best:

In the current example we try to calculate the projection of the endsequent merged with  the clause C = :- p(s(s(a))), p(a) for the formula ((p(s(s(s(a))))∨¬p(s(s(a))))∧(p(s(a))∨¬p(a))) i.e. we want to geenrate a proof of:


:- ((p(s(s(s(a))))∨¬p(s(s(a))))∧(p(s(a))∨¬p(a))), p(s(s(a))), p(a) 


PCNF propagates C over the decomposition of the conjunction and expects one of the  conjuncts to contain C (the other conjunct is weakened in). In fact, the left conjunct only derives :- p(s(s(s(a)))) while the right one derives :- p(a). During the application of the conjunction rule, the context is merged and we would correctly get C.

I would go to change the case distinction of the projections to require that only a subset of C needs to be derived during recursion and weaken in missing literals later. But I'm a bit uncertain if this is still sound, so can anyone check the claim?

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on November 12, 2013 06:38:26_

Hi Martin,

thanks for your comments. I think you were right to say that weakening is not necessary.

Let me write how I see the algorithm (I have only looked superficially, I may very well have the wrong thing in mind, please correct me if I'm wrong):

Let F be a formula, C \in CNF(\neg F). You want to construct a proof of C \merge (:- F). This is your induction invariant. The bug results since you assume that if C \in CNF( F \lor G ) then either C \in CNF(F) or C \in CNF(G), which is wrong in this example. What is true is that if C \in CNF( F \lor G ) then there exist clauses C_1, C_2 such that C_1 \in CNF(F) and C_2 \in CNF(G) and C_1 \merge C_2 = C.

So it seems it should suffice to look for clauses C_1, C_2 in the respective CNFs having that property, and to apply the recursive call to these clauses. As you have observed, since they will be combined by a binary rule, the correct proof of C \merge (:- F) will be produced.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 12, 2013 07:43:29_

This issue was closed by revision r1733 .

**Status:** Fixed

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 12, 2013 07:46:22_

Thanks for the clarification, Daniel - the changes are checked in now. Can you test also other examples?

By the way: I think we have at least 3 variations of addWeakeneings/Contractions. I moved my version now to the other in lkalgorithms, but tomer's version is still in resolutionalgorithms (and probably cvetan also wrote one for acnf construction).
