### ISSUE TITLE
RobinsonToLK has problems with symmetry

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#248]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on November 15, 2013 11:32:32_

What steps will reproduce the problem? Let tptp.in be the following file:

fof( to_prove, conjecture, 'a' = 'b' | 'b' != 'a').

Then do

tptp_to_ladr \< tptp.in > p9.in
prover9 \< p9.in >p9.out

And, in the CLI,

loadProver9LKProof("p9.out")
loadProver9Proof("/tmp/p9/p9.out") What is the expected output? What do you see instead? Expected output is an LK proof. We get the following exception instead:

java.lang.IllegalArgumentException: Clause [ :- ] is not reflexivity and not contained in CNF(-s) [
=(ladr1, ladr0) :- ;
 :- =(ladr0, ladr1)
]

Note that the loadProver9Proof indeed returns a resolution refutation - but in this case, it is the trivial one consisting just of the empty clause!

Furthermore, I think when refuting a CNF F, prover9 allows to use as assumptions in the refutation clauses which are obtained from F *modulo symmetry*. This causes an analogous exception.

What to do: I think already the parsing done in loadProver9Proof must be fixed to handle symmetry 'correctly' (i.e. in this case, one would expect a proof using one paramodulation and one resolution step, starting from the clauses { :- a = b; b = a :- }, instead of the trivial refutation).

_Original issue: http://code.google.com/p/gapt/issues/detail?id=248_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 15, 2013 02:58:58_

Hi Daniel!

The thing with the trival example is that it has only one inference:

1 ladr1 = ladr0 | ladr0 != ladr1 # label(to_prove) # label(conjecture) # label(non_clause) # label(goal).  [goal].
2 $F # label(to_prove) # label(conjecture) # answer(to_prove).  [deny(1)].

So we chould get the trivial proof Axiom( :- ) but we can't properly do a CNF projection to :- yet.

I'm not sure, if this is also the reason of the other failures - i'll check Stefan's output.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on November 15, 2013 03:06:06_

Yes, the prover9 proof contains 1 inference, but the parsed proof contains 0 inferences.

I thought the semantics of loadProver9Proof should be to return a resolution/paramodulation proof of the empty sequent which has at the leaves the clauses from the input file. To do this in this case, apparently the parser should know how to handle this "deny(1)" inference of prover9.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 15, 2013 03:10:37_

This inference is already removed by the ivy transformation:

[marty@kushiel gapt]$ cat trivialeq.out | prooftrans | prooftrans ivy
;; ============================== prooftrans ============================
;; Prover9 (64) version 2009-11A, November 2009.
;; Process 12239 was started by marty on kushiel,
;; Fri Nov 15 11:52:12 2013
;; The command was "prover9".
;; ============================== end of head ===========================

;; BEGINNING OF PROOF OBJECT
(
(2 (input) false NIL)
)
;; END OF PROOF OBJECT

I agree the example above needs to be correctly parsed, but i don't think it is the source of the majority of Stefan's errors, because :- is rarely directly contained in the CNF.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on November 15, 2013 03:17:12_

Yes, but the symmetry problem occurs also elsewhere, as I mentioned in my first comment.

Use tptp.in:
fof( to_prove, conjecture, 'a' = 'b' & 'c' = 'b' => 'a' = 'c' ).

to get the exception
java.lang.IllegalArgumentException: Clause [ :- =(ladr1, ladr2)] is not reflexivity and not contained in CNF(-s) [
 :- =(ladr2, ladr1);
 :- =(ladr0, ladr1);
=(ladr2, ladr0) :- 
]

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 15, 2013 03:30:41_

By the way, what is weird is that i cannot reproduce the errors in Stefan's file:

 val files = List("../testing/prover9-TSTP/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out", "../testing/prover9-TSTP/KLE/KLE064+1/Prover9---1109a.THM-Ref.s.out", "../testing/prover9-TSTP/KLE/KLE064+1/Prover9---1109a.THM-Ref.s.out", "../testing/prover9-TSTP/GRP/GRP729-1/Prover9---1109a.UNS-Ref.s.out")

 files map (loadProver9LKProof(_))

returns without exceptions:

Memoization saved 0 calls!
Memoization saved 0 calls!
Memoization saved 0 calls!
Memoization saved 0 calls!
res20: List[at.logic.calculi.lk.base.LKProof] = List(ContractionLeftRuleType(∀B.∀C.∀A.(¬member(A, intersection(B, C))∨member(A, C)), ∀B.∀A.(¬member(A, complement(B))∨¬member(A, B)), ∀B.∀C.∀A.(¬member(A, B)∨(¬member(A, C)∨member(A, intersection(B, C)))), ∀A.subclass(A, universal\_class), ∀B.∀C.∀A.(¬subclass(A, B)∨(¬member(C, A)∨member(C, B))), ∀A.(=(A, null\_class)∨member(regular(A), A)), ∀B.∀C.∀A.=(intersection(cross\_product(A, B), C), restrict(C, A, B)), ¬=(restrict(null\_class, x, y), null\_class), ∀B.∀C.∀A.=(intersection(A, cross\_product(B, C)), restrict(A, B, C)) :- , CutRuleType(∀B.∀C.∀A.(¬member(A, intersection(B, C))∨member(A, C)), ∀B.∀A.(¬member(A, complement(B))∨¬member(A, B)), ∀B.∀C.∀A.(¬member(A, B)∨(¬member(A, C)∨member(A, intersection(B, C)))), ∀A.subclass(A, universal\_c...

I will try to rebuild gapt and try again, but this confuses me. I will be offline for the next hours, but i'll look into the symmetry case in the evening.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on November 15, 2013 03:36:07_

The prover9 inputs are generated by the cut-introduction code. Maybe Stefan can supply the TPTP input files generated by his cut-introduction test-run?

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on November 15, 2013 04:12:15_

Martin, the bug can be reproduced by calling

cutIntroExp( loadProver9LKProof( "../testing/prover9-TSTP/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out" ), new at.logic.provers.prover9.Prover9Prover() )

As Daniel said, it does not happen in the initial call to prover9 that parses the TSTP-proof but rather in a later call done during cut-introduction.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 18, 2013 09:29:48_

A ropert from today:

There was a bug in CNF construction where i just commited the fix (we didn't construct clause sets but multisets). What is still missing is the following problem:

Prover9 does some preprocessing during CNF transformation which includes:

*) flipping equations
*) simplifying clauses (up to :-, which can not come directly from the cnf transformation of a formula )

the problem with these is that they are transparent in the proof object. prover9's output contains at leats an inference 2: ... deny(1), but after the transformation even this little information is gone.

What I can try is to find out which optimizations are done and add these to the code constructing the PCNF (which at the moment correctly complains that the clause given by ivy is not contained in the cnf of the end-sequent). Where I am a bit hesitant is to customize Robinson2LK for Prover9, since the input might come from somewhere else. It is possible to add additional possible clauses to the cnf and handle this more or less cleanly but it still feels like a hack. What are your opinions(since we don't meet on Wednesday)?

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on November 18, 2013 09:42:04_

Thanks for investigating, Martin!

What about changing the code that parses Ivy to a RobinsonProof such that e.g. the application of symmetry is added to the parsed proof in the form of paramodulation? The intended semantics of the Ivy to RobinsonProof parsing should be, in my opinion, that the parsed RobinsonProof has at the leaves exactly the clauses from the CNF handed to prover9. Then neither the PCNF nor the Robinson2LK code needs to be changed.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 18, 2013 10:06:36_

At the moment, the ivy construction does not know about the end-sequent, but this is definitely another possibilty.

Regarding the characteristics of the ivy proof: the leaves of the ivy proof are exactly the clauses prover9 uses. Prover9 just does more than cnf transformation on the input formula. Still, the transformation is somehow part of the proof, so ivy feels like a better place to me than the pcnf construction.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on November 18, 2013 10:41:22_

Would it be an option to do the CNF transformation within gapt instead of letting prover9 do it?

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 08, 2013 01:17:12_

r1818 is a change that concerns this issue: I added a method to "repair" a resolution refutation that uses initial clauses modulo symmetry to one where these clauses are derived from the "correct" clauses by paramodulation.

This fixes the problem raised in comment `#4`.

Try the following, which used to fail and now works:

Do:

echo "fof( to_prove, conjecture, 'a' = 'b' & 'c' = 'b' => 'a' = 'c' )." > tptp.in
tptp_to_ladr \< tptp.in > p9.in
prover9 \< p9.in >p9.out

And, in the CLI,

loadProver9LKProof("p9.out")

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on December 08, 2013 01:47:48_

Daniel, thanks for looking into this!

However, there is still a bug: doing

loadProver9LKProof( "../testing/prover9-TSTP/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out" )

in the CLI ends with a number of warnings in fixSymmetry and then:
java.lang.IndexOutOfBoundsException: 1
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:52)
        at scala.collection.immutable.List.apply(List.scala:84)
        at at.logic.algorithms.resolution.fixSymmetry$.rec(symmetry.scala:123)
        at at.logic.algorithms.resolution.fixSymmetry$.rec(symmetry.scala:129)

This command used to work in r1817 .

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 08, 2013 03:40:11_

In r1819 ,

loadProver9LKProof( "../testing/prover9-TSTP/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out" )

works again, but 

cutIntroExp( loadProver9LKProof( "../testing/prover9-TSTP/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out" ), new at.logic.provers.prover9.Prover9Prover() )

still does not: it fails during TPTP export now, but I don't know why.

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on January 26, 2015 05:29:07_

Closing this issue as the problem in the last comment is no longer related to symmetry.

**Status:** Fixed
