### ISSUE TITLE
MiniSAT fails to prove deep formula of expansion proof

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#253]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on November 30, 2013 19:56:14_

The test "load veriT proofs pi and verify the validity of Deep(pi) using MiniSAT" in MiscTest.scala:178 fails as MiniSAT claims that the formula is not valid. Prover9 is able to prove it.

The test is currently skipped. MiniSAT already fails for the second test file test1.verit

_Original issue: http://code.google.com/p/gapt/issues/detail?id=253_

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on December 04, 2013 02:22:12_

**Cc:** fra...@gmail.com giselle....@gmail.com  
**Labels:** -Milestone- -Priority- Priority-Medium

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 03, 2014 04:54:00_

Sebastian, could you please check whether your recent commit r2156 fixes this issue? You can do so by removing the skip-test line in MiscTest.scala:187. If yes, this issue can be closed.

**Cc:** sziv...@gmail.com

**Comment by newca12** [comment]
_From [sziv...@gmail.com](https://code.google.com/u/107462141115948183633/) on October 03, 2014 08:27:51_

Unfortunately the issue is not fixed yet.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 09, 2014 01:44:34_

As Sebastian has found out there is a mixup between the FOL- and the HOL-layer in this issue. To reproduce, do the following in the CLI:

import at.logic.parsing.veriT.VeriTParser
import at.logic.calculi.expansionTrees._
import at.logic.provers.minisat.MiniSATProver

val filename = "../testing/veriT-SMT-LIB/QF_UF/eq_diamon/eq_diamond1.smt2.proof_flat"
val p = VeriTParser.getExpansionProof(filename).get
val seq = toDeep(p)
(new MiniSATProver).isValid(seq)

This results in:
java.lang.ClassCastException: at.logic.language.hol.BottomC$ cannot be cast to at.logic.language.fol.FOLExpression
  at at.logic.language.fol.FOLFactory$$anon$2.<init>(base.scala:84)
  at at.logic.language.fol.FOLFactory$.createApp(base.scala:84)
  at at.logic.language.fol.FOLFactory$.createApp(base.scala:71)
  at at.logic.language.hol.HOLApp$.apply(base.scala:37)
  at at.logic.language.hol.Imp$.apply(hol.scala:160)
  at at.logic.provers.minisat.MiniSATProver.isValid(MiniSAT.scala:179)
  ... 33 elided

VeriTParser produces FOLFormulas while MiniSATProver works in HOL. The bottom constant enters the picture as empty disjunction produced by the rhs of the sequent.

Daniel, any suggestion how to fix this?

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 09, 2014 02:26:56_

One more comment: this also happens for the original test file of the integration test. Use 

val filename = "integration_tests/misc_test/src/test/resources/test1.verit"

in the above CLI-commands.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on October 09, 2014 04:19:18_

This issue was closed by revision r2176 .

**Status:** Fixed

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on October 09, 2014 04:19:26_

Problem summary: The logical symbols exist in multiple copies: one bottom in HOL, one bottom in FOL, etc. This was a design decision at some point. The problem is that without context, we sometimes don't know which layer to take a constant from (see e.g. comment at hol.scala:144).

Proposed solution: When constructing a FOL expression, we check whether one of the constituents of the expression is a known logical constant from the HOL layer. If it is, we replace it by the appropriate constant from the FOL layer.

The proposed solution fixes the bug, and I could not find a more appealing solution. I commited this solution as r2176 .

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 09, 2014 05:52:54_

Maybe this is a naive question... but why is miniSAT implemented for HOL if
it works only on the propositional level?

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on October 09, 2014 06:02:18_

The Prover trait is defined at the HOL layer (a design choice, see also the comment in Prover.scala). The Prover trait also implements some code translating a sequent into a formula. That's how HOL stuff turned up in MiniSAT (which implements the Prover trait). Does that clear things up resp. make sense to you? :-)

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 09, 2014 06:14:06_

Oh I see... It makes sense if we want to use a HOL prover at some point.
Another solution would be just to change veriT parsing to return
HOLFormulas, but I guess this problem will eventually occur elsewhere.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 09, 2014 06:18:53_

It does occur elsewhere, e.g. when applying minisat to the deep formula of an expansion sequent obtained from loadProver9LKProof. In fact, it occurs whenever a FOLFormula is sent into minisat (and happens to need a logical constant).

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 09, 2014 06:29:34_

Even though the HOL/FOL-intermixing is fixed I am reopening this issue because the integration test in MiscTest.scala:186 still fails. In fact, minisat (as expected) returns true on isValid for test{0,1,2,4}.verit in integration_tests/misc_test/src/test/resources/ but on test3.verit it returns false. To reproduce in the CLI, do:

import at.logic.parsing.veriT.VeriTParser
import at.logic.calculi.expansionTrees.toDeep
val filename = "integration_tests/misc_test/src/test/resources/test3.verit"
val p = VeriTParser.getExpansionProof(filename).get
val seq = toDeep(p)
(new MiniSATProver).isValid(seq)

This returns false but should return true.

**Status:** Started  
**Owner:** sziv...@gmail.com

**Comment by newca12** [comment]
_From [sziv...@gmail.com](https://code.google.com/u/107462141115948183633/) on October 09, 2014 06:32:26_

In that case I will go right back to investigating.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 14, 2014 00:07:28_

There is (at least) one other veriT-proof which produces the same bug:
val filename = "../testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl419.smt2.proof_flat"

**Comment by newca12** [comment]
_From [sziv...@gmail.com](https://code.google.com/u/107462141115948183633/) on October 29, 2014 07:01:16_

I imported the proof from the file testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl055.smt2.proof_flat and looked at it in prooftool. The expansion sequent that the parser reads from the file is clearly not valid: It only consists of equality axioms and a long conjunction of inequalities of the form op(ei, ej) != op(ek, el). Clearly this sequent can be realized by choosing all those elements to be unequal.

It appears that there are clauses in the file that the parser overlooks.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 29, 2014 07:25:52_

I have looked at this with Sebastian today.

The long conjunction he mentions seems to be (a symmetry-variant of) .c7 in the input file.

It seems that the parsing of veriT is buggy here - in particular the comment at VeriTParser.scala:393 made me wonder: do we ignore all but the last input formula? what happens if more than one are logically necessary?

Giselle, could you please have a look at this once you are settled in Paris? Thanks! I hope your move went well by the way :-)

One further comment: this bug applies to 119 of the files in our veriT-collection. I am attaching the full list (generated by Sebastian).

**Attachment:** [invalidProofs.txt](http://code.google.com/p/gapt/issues/detail?id=253#hc16)

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 30, 2014 07:13:17_

Hi Stefan,

I still have no internet at home, so my replies will probably be a bit
delayed, but I will check what is going on.

Best,
Giselle

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 31, 2014 08:13:12_

Hi,

Things are getting back on track now in Paris :)
I looked at this issue and here's an update.

The comment at VeriTParser.scala:393 still holds, we ignore all the formulas of the preamble (which includes 'input', 'tmp_distinct_elim', 'tmp_alpha_conv' and 'tmp_let_elim') but the last one. This was because all these operations were doing was eliminating definitions, renaming, etc, and we did not really need the intermediary results (note that we don't even parse the let constructions - line 487). The only thing we were interested was on the final result of all these transformations, i.e., the input formula per se. 
What we did not predict was the existence of other inputs which were already in normal form and were clauses used in the proof. This is the case for the "../testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl419.smt2.proof_flat" example.

Since now we don't know which preamble formulas to use and which to ignore (those with 'let' and 'distinct' for example, that will still be further processed before the proof) I will do the following: all the formulas from the preamble will be stored in a hash table using their labels as a key. When parsing the proof, I will collect the clauses used and, if they are in the preamble, I will mark it as a clause used in the proof. In the end, those will be the preamble clauses that will be taken. Is it clear? Do you think it's a good solution?

Cheers,
Giselle

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 31, 2014 08:28:44_

Hi Giselle,

Good to hear that you are getting settled in Paris :)

The solution you propose sounds good to me. 

It does however seem to make one assumption: If I remember correctly the veriT output format describes a a tree, so when you say "preamble" you mean that the input clauses of the tree (including NF transformations) are described before the inner nodes (e.g. resolution steps). Is this assumption justified? Or may it happen that some input clauses are described, then some resolutions on these clauses and then, again, further input clauses? It seems that the format - in principle - would allow this but veriT does not use this option...

In any case, this assumption should be documented.

Best regards,
Stefan

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 31, 2014 10:01:00_

Hi Stefan,

I just committed the changes. I will not dare close this issue though :)
I am setting a small test to run on the server while I go home. It will test all the proof that Sebastian identified. Hopefully it will finish in a few hours.

Regarding the assumption on the order of the clauses, if this does not hold parsing would fail. But I put a comment there in any case.

Best,
Giselle

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on November 03, 2014 06:51:18_

Hi,

I left the test running over the weekend and it was ok for the first 7 proofs... unfortunately minisat takes an enormous amount of time for each example and I killed the tests after 2 days. Is this expected or is it another issue?

Best,
Giselle

**Comment by newca12** [comment]
_From [sziv...@gmail.com](https://code.google.com/u/107462141115948183633/) on November 03, 2014 06:59:48_

I'm inclined to think that it's a result of the complete proofs actually being pretty large. I'm currently running the test as well, starting with the smaller files, and so far it hasn't found any invalid proofs.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on November 05, 2014 05:10:23_

Giselle, I believe that your recent commit has fixed the issue.

In principle it should be possible to verify something produced by veriT with minisat (in reasonable time).

I looked at the output of "top" on one example which takes very long. It shows 100% CPU usage for java for quite a while but nothing for minisat. My suspicion is that we spend this time in the CNF transformation. I have asked Sebastian to verify this and if it is the case substitute the Tseitin-transformation in MiniSATProver.

Before finally closing it let us wait for this to be completed.

**Comment by newca12** [comment]
_From [sziv...@gmail.com](https://code.google.com/u/107462141115948183633/) on November 05, 2014 07:07:44_

Just now I timed MiniSAT for one file. Computing the CNF took 4 and 1/2 minutes, solving a third of a second. I will modify MiniSAT to use the Tseitin transformation.

**Comment by newca12** [comment]
_From [sziv...@gmail.com](https://code.google.com/u/107462141115948183633/) on November 06, 2014 06:35:38_

Using the Tseitin transformation, the tests run in acceptable time and MiniSAT now returns valid for all files.

Note that I haven't removed the skip for the test that originally raised this issue because doing so causes a cut-introduction test to take forever. I have no idea why that is.

**Comment by newca12** [comment]
_From [sziv...@gmail.com](https://code.google.com/u/107462141115948183633/) on November 07, 2014 05:18:23_

The test goes through now.

**Status:** Fixed
