### ISSUE TITLE
Prover9 fails to prove deep formula of expansion proof in reasonable time

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#254]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on November 30, 2013 20:00:48_

The test "load veriT proofs pi and verify the validity of Deep(pi) using Prover9" in MiscTest.scala:202 takes more than 30 minutes on my machine. I stopped it at that point since the sequent doesn't seem to justify a this running time.

The test is currently skipped, the problem occurs at the third input file (test2.verit). You can uncomment the printlns in the test to see what is happening.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=254_

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on December 04, 2013 02:27:15_

prover9 is a first-order prover and hence not as efficient on quantifier-free formulas as the SMT-solver veriT. It seems that Deep(test2.verit) is just too large for a first-order prover to handle.

On the other hand: minisat should be able to prove all deep formulas of expansion proofs generated from other provers.

Therefore this test at MiscTest.scala:202 should be changed to read prover9-output and verify the deep formulas thus obtained by minisat.

**Labels:** -Milestone- -Priority- Priority-Medium

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on December 09, 2013 06:49:17_

As discussed last Wednesday, I should correct my previous comment: deep formulas obtained from expansion proofs of prover9-output should be verified by veriT (not by minisat) because these formulas are not propositional tautologies but provable only in the theory of equality (which veriT implements).

**Comment by newca12** [comment]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on December 10, 2013 07:12:19_

I tried to run VeriTProver on it, but the executable of veriT I use [1] doesn't support the command line parameter "--proof-version=1". Is some kind of special version required? (veriT is not mentioned here: https://code.google.com/p/gapt/wiki/Installation. )

[1] http://www.verit-solver.org/veriT-download.php Also, which prover9 output files are supposed to be tested? For some of them I get an OutOfMemoryException (GRA014+1.out), for others (cad13example.out), it seems that FO-Expressions are not detected as FO-Expression:

scala> val x = Prover9.parse_prover9("./provers/prover9/target/test-classes/cade13example.out")
x: (at.logic.calculi.resolution.robinson.RobinsonResolutionProof, at.logic.calculi.lk.base.types.FSequent) = (Res( :- , Res( :- q(a, f(a)), Fac( :- p(a), Res( :- p(a), p(a), InitialType( :- p(a), p(b)), Res(p(b) :- p(a), Res( :- p(a), q(b, f(b)), InitialType( :- p(a), p(b)), Inst(p(b) :- q(b, f(b)), Inst(p(v0) :- q(v0, f(v0)), Res(p(v100) :- q(v100, f(v100)), Inst( :- q(v100, f(v100)), q(v100, g(v100)), InitialType( :- q(v0, f(v0)), q(v0, g(v0))), Map(v0 -> v100)), Inst(p(v100), q(v100, g(v100)) :- , InitialType(p(v0), q(v0, v1) :- ), Map(v1 -> g(v100), v0 -> v100)), Map()), Map(v100 -> v0)), Map(v0 -> b)), Map()), Inst(p(b), q(b, f(b)) :- , InitialType(p(v0), q(v0, v1) :- ), Map(v1 -> f(b), v0 -> b)), Map()), Map()), Map()), Inst(p(a) :- q(a, f(a)), Inst(p(v0) :- q(v0, f(v0)), Res(p(v1...

scala>  val lkProof = new Prover9Prover().getLKProof(x._2)
WARNING: Trying to do a string conversion on a term which is not a (full) FOL expression: (∀:((ι->ο)->ο))(q_{1}:(ι->ο))
scala.MatchError: (∀:((ι->ο)->ο))(q_{1}:(ι->ο)) (of class at.logic.language.fol.FOLFactory$$anon$2)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:88)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:87)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:87)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.exportFormula(TPTPFOLExporter.scala:61)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptp_proof_problem(TPTPFOLExporter.scala:37)
	at at.logic.provers.prover9.Prover9$.writeProofProblem(Prover9.scala:44)
	at at.logic.provers.prover9.Prover9$.prove(Prover9.scala:155)
	at at.logic.provers.prover9.Prover9$.prove(Prover9.scala:275)
	at at.logic.provers.prover9.Prover9Prover.getRobinsonProof(Prover9.scala:367)
	at at.logic.provers.prover9.Prover9Prover.getLKProof(Prover9.scala:388)
	at .<init>(<console>:70)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:745)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:790)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:702)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:566)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:573)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:576)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:867)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:83)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
	at at.logic.cli.CLIMain$.main(CLIMain.scala:63)
	at at.logic.cli.CLIMain.main(CLIMain.scala)

**Owner:** b.mallin...@gmx.at

**Comment by newca12** [comment]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on December 11, 2013 14:37:01_

Implemented in r1828 (though currently skipped)

**Status:** Fixed
