### ISSUE TITLE
generalized cut-introduction fails with FOLVar match error

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#257]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on December 09, 2013 14:06:12_

Many examples in our test-suite for cut-introduction fail when using generalized cut-introduction with:

scala.MatchError: v102 (of class at.logic.language.fol.FOLVar)
	at at.logic.language.fol.Utils$.fromFunc(utils.scala:57)
	at at.logic.algorithms.cutIntroduction.Generalized.Deltas$$anonfun$at$logic$algorithms$cutIntroduction$Generalized$Deltas$$commonFuncHead$1$$anonfun$apply$2.apply(Deltas.scala:334)
[...]

For concrete examples, do the following in the CLI:
cutIntroG( loadProver9LKProof( "../testing/prover9-TSTP/SYN/SYN039-1/Prover9---1109a.UNS-Ref.s.out" ), NoConstraint )
cutIntroG( loadProver9LKProof( "../testing/prover9-TSTP/LCL/LCL182-3/Prover9---1109a.UNS-Ref.s.out" ), NoConstraint )
cutIntroG( loadProver9LKProof( "../testing/prover9-TSTP/SYN/SYN332-1/Prover9---1109a.UNS-Ref.s.out" ), NoConstraint )
cutIntroG( loadProver9LKProof( "../testing/prover9-TSTP/REL/REL008+4/Prover9---1109a.THM-Ref.s.out" ), NoConstraint )

_Original issue: http://code.google.com/p/gapt/issues/detail?id=257_

**Comment by newca12** [comment]
_From [janos.ta...@gmail.com](https://code.google.com/u/110287254390562270748/) on December 11, 2013 05:48:49_

This issue was closed by revision r1825 .

**Status:** Fixed
