### ISSUE TITLE
LKtoLKsk fails on the n-tape proof

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#258]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 09, 2013 14:21:14_

This error comes with a change in llk parsing (axiom instantiations are not done by cut anymore) and produces an error in LKtoLKsk which I don't fully understand. On the commandline you can reporoduce it by issuing the following commands:

    val p = loadLLK("algorithms/hlk/src/test/resources/tape3.llk")
    val elp = eliminateDefinitions(p, "TAPEPROOF")
    val selp = at.logic.transformations.skolemization.lksk.LKtoLKskc(regularize(elp)._1)

and get:
at.logic.calculi.lk.base.LKUnaryRuleCreationException: Could not create lk rule Auxiliary formula occurrence label of ForallSkLeftRule does not contain substitution term. Label: Set(), substitution term: 0:ι from parent List(∀y:ι.=(bm(+(0:ι, 1:ι):ι, +(y:ι, 1:ι):ι):ι, bm(0:ι, y:ι):ι): o (label: Set())) :- List(=(bm(+(0:ι, 1:ι):ι, +(0:ι, 1:ι):ι):ι, bm(0:ι, 0:ι):ι): o (label: Set())) with auxiliary formulas ∀y:ι.=(bm(+(0:ι, 1:ι):ι, +(y:ι, 1:ι):ι):ι, bm(0:ι, y:ι):ι): o
	at at.logic.calculi.lksk.ForallSkLeftRule$.apply(lksk.scala:110)
	at at.logic.algorithms.lksk.applySubstitution$.apply(substitution.scala:56)
	at at.logic.algorithms.lksk.applySubstitution$.apply(substitution.scala:82)
	at at.logic.algorithms.lksk.applySubstitution$.apply(substitution.scala:82)
[...]
	at at.logic.transformations.skolemization.lksk.LKtoLKskc$.rec(lksk.scala:99)
	at at.logic.transformations.skolemization.lksk.LKtoLKskc$.rec(lksk.scala:89)
	at at.logic.transformations.skolemization.lksk.LKtoLKskc$.rec(lksk.scala:179)
	at at.logic.transformations.skolemization.lksk.LKtoLKskc$.rec(lksk.scala:286)
	at at.logic.transformations.skolemization.lksk.LKtoLKskc$.rec(lksk.scala:286)
	at at.logic.transformations.skolemization.lksk.LKtoLKskc$.transformWeakQuantRule(lksk.scala:390)
	at at.logic.transformations.skolemization.lksk.LKtoLKskc$.rec(lksk.scala:81)
[...]

With the commands:

    val selp = try { at.logic.transformations.skolemization.lksk.LKtoLKskc(regularize(elp)._1) } catch { case LKUnaryRuleCreationException(_,p,aux::Nil) => println(aux); p }
    prooftool(selp)

you can see the subproof with the wrong label, the logger should print the end-sequent of the parent in the rec(...) call, but i can't really match the labels.

Might this be failing because the selection of aux formulas is done by formula which might have the wrong label if there is more than one occurrence of aux in a sequent?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=258_

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 09, 2013 07:46:35_

I'll take a look at this.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 09, 2013 08:25:24_

Fixed in r1822 .

**Status:** Fixed

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 10, 2013 00:03:20_

Thanks a lot, it worked!

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 10, 2013 00:18:37_

Thanks for the detailed bug report :-)
