### ISSUE TITLE
veriT fails with syntax error in toProve.smt

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#259]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on December 12, 2013 16:31:09_

In the CLI do the following:

cutIntroExp( loadProver9LKProof( "../testing/prover9-TSTP/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out" ), new at.logic.provers.eqProver.EquationalProver() )

This fails with

error : syntax error on line 11 : [�]
java.lang.RuntimeException: Nonzero exit value: 1
	at scala.sys.package$.error(package.scala:27)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:131)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:101)
	at at.logic.provers.veriT.VeriTProver$.isValid(VeriTProver.scala:19)

This may be connected to the unicode bottom symbol in toProver.smt

_Original issue: http://code.google.com/p/gapt/issues/detail?id=259_

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on December 12, 2013 08:33:46_

This issue was closed by revision r1829 .

**Status:** Fixed

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on December 12, 2013 08:51:12_

There are some more unicode symbols. Generalized cut-introduction uses α_0,α_1,... as eigenvariables. The (standard) cut-introduction presumably uses α at this point which does seem to work.

This makes most calls like

cutIntroG( LinearExampleProof( 4 ), NoConstraint, new at.logic.provers.eqProver.EquationalProver() )

which combine cutIntroG and EquationalProver fail.

**Status:** Started  
**Owner:** giselle....@gmail.com  
**Cc:** stefan.hetzl

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 09, 2014 05:50:18_

Fixed in r1833 using org.apache.commons.lang3.StringEscapeUtils

**Status:** Fixed
