### ISSUE TITLE
algorithms.lk.eliminiateDefinitions ExistsRight QuantifierException

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#260]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on December 22, 2013 18:39:05_

When applying lk.eliminateDefinitions to the prime proof in PrimeProofTest.scala, I get the following error (4 times):

The system should::parse, skolemize, and export the clause set in TPTP of the first-order prime proof, n=0(at.logic.integration_tests.PrimeProofTest)  Time elapsed: 1.702 sec  \<<< ERROR!
at.logic.calculi.lk.quantificationRules.LKQuantifierException: Substituting the term 1:ιback into the given formula =(1:ι, 1:ι): o gives ∈(1, set_1(1)) instead of =(1, 1))
	at at.logic.calculi.lk.quantificationRules.WeakRuleHelper.getTerms(quantificationRules.scala:481)
	at at.logic.calculi.lk.quantificationRules.ExistsRightRule$.apply(quantificationRules.scala:172)
	at at.logic.algorithms.lk.eliminateDefinitions$.rec(lk.scala:235)
	at at.logic.algorithms.lk.eliminateDefinitions$.rec(lk.scala:212)
	at at.logic.algorithms.lk.eliminateDefinitions$.handleDefinition(lk.scala:256)
	at at.logic.algorithms.lk.eliminateDefinitions$.rec(lk.scala:225)
	at at.logic.algorithms.lk.eliminateDefinitions$.rec(lk.scala:217)
	at at.logic.algorithms.lk.eliminateDefinitions$.rec(lk.scala:118)
	at at.logic.algorithms.lk.eliminateDefinitions$.rec(lk.scala:118)
	at at.logic.algorithms.lk.eliminateDefinitions$.apply(lk.scala:109)
	at at.logic.integration_tests.PrimeProofTest$$anonfun$1.at$logic$integration_tests$PrimeProofTest$$anonfun$$prime1$1(PrimeProofTest.scala:170)
	at at.logic.integration_tests.PrimeProofTest$$anonfun$1$$anonfun$apply$12.apply(PrimeProofTest.scala:274)
	at at.logic.integration_tests.PrimeProofTest$$anonfun$1$$anonfun$apply$12.apply(PrimeProofTest.scala:274)

Steps to reproduce:
Add the following line in prime1() after "val proof = proofdb.proofs.head._2":
val definitionFreeProof = eliminateDefinitions(proof)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=260_

**Comment by newca12** [comment]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on January 08, 2014 06:22:17_

For the moment, eliminateDefinitions is not supposed to work on the whole prime proof.

**Status:** WontFix
