### ISSUE TITLE
IllegalArgumentException when extracting expansion trees from LK proof

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#261]
_From [janos.ta...@gmail.com](https://code.google.com/u/110287254390562270748/) on January 05, 2014 17:40:42_

Since revision `#1841` , an IllegalArgumentException is sometimes thrown when extracting expansion trees.

The following commands produce the problem:

\> cutIntro( loadProver9LKProof( "../testing/prover9-TSTP/SYN/SYN039-1/Prover9---1109a.UNS-Ref.s.out" ))
OR
\> cutIntroG( loadProver9LKProof( "../testing/prover9-TSTP/SYN/SYN039-1/Prover9---1109a.UNS-Ref.s.out" ), NoConstraint )

java.lang.IllegalArgumentException: Bug in merge in extractExpansionTrees. By Construction, the trees to be merge should have the same structure, which is violated.
    at at.logic.calculi.expansionTrees.merge$.doApplyMerge(expansionTrees.scala:610)
    at at.logic.calculi.expansionTrees.merge$.at$logic$calculi$expansionTrees$merge$$detectAndMergeMergeNodes(expansionTrees.scala:567)
    at at.logic.calculi.expansionTrees.merge$.main(expansionTrees.scala:502)
    at at.logic.calculi.expansionTrees.merge$.applyRec$1(expansionTrees.scala:472)
    at at.logic.calculi.expansionTrees.merge$.apply(expansionTrees.scala:484)
    at at.logic.transformations.herbrandExtraction.extractExpansionTrees$.apply(expansionTrees.scala:16)
    at at.logic.algorithms.cutIntroduction.Generalized.CutIntroduction$.apply(CutIntroduction.scala:58)
    at at.logic.cli.GAPScalaInteractiveShellLibrary.cutIntroG$.apply(GAPScalaInteractiveShellLibrary.scala:639)
(...)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=261_

**Comment by newca12** [comment]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on January 05, 2014 08:45:21_

This was somewhat broken before, but worked for most cases. It currently always fails when merging a formula that was introduced by a weakening. I'm working on a fix.

**Comment by newca12** [comment]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on January 06, 2014 12:06:36_

Fixed in r1846

**Status:** Fixed
