### ISSUE TITLE
Expansion Tree extraction fails in new lambda branch:

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#265]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on May 07, 2014 13:55:43_

On the cli call:

    val pdb = loadLLK("algorithms/llk/src/test/resources/pigeon32.llk")
    extractExpansionTrees(pdb.proof("PROOF"))

results in:
java.lang.IllegalArgumentException: Bug in merge in extractExpansionTrees. By Construction, the trees to be merge should have the same structure, which is violated for:
Atom(=:(ι->(ι->ο))(hole:(ι->ι)(pigeon1:ι):ι, 0:ι): o)∧Atom(=:(ι->(ι->ο))(hole:(ι->ι)(pigeon2:ι):ι, 0:ι): o)
Atom((=:(ι->(ι->ο))(hole:(ι->ι)(pigeon1:ι):ι, 0:ι): o∧=:(ι->(ι->ο))(hole:(ι->ι)(pigeon2:ι):ι, 0:ι): o))
	at at.logic.calculi.expansionTrees.merge$.doApplyMerge(expansionTrees.scala:693)
	at at.logic.calculi.expansionTrees.merge$.start_op2$2(expansionTrees.scala:643)
	at at.logic.calculi.expansionTrees.merge$.doApplyMerge(expansionTrees.scala:677)
	at at.logic.calculi.expansionTrees.merge$.at$logic$calculi$expansionTrees$merge$$detectAndMergeMergeNodes(expansionTrees.scala:625)
	at at.logic.calculi.expansionTrees.merge$$anonfun$at$logic$calculi$expansionTrees$merge$$detectAndMergeMergeNodes$1.apply(expansionTrees.scala:605)
	at at.logic.calculi.expansionTrees.merge$$anonfun$at$logic$calculi$expansionTrees$merge$$detectAndMergeMergeNodes$1.apply(expansionTrees.scala:603)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at at.logic.calculi.expansionTrees.merge$.at$logic$calculi$expansionTrees$merge$$detectAndMergeMergeNodes(expansionTrees.scala:603)
	at at.logic.calculi.expansionTrees.merge$.doApplyMerge(expansionTrees.scala:670)
	at at.logic.calculi.expansionTrees.merge$.doApplyMerge(expansionTrees.scala:680)
	at at.logic.calculi.expansionTrees.merge$.at$logic$calculi$expansionTrees$merge$$detectAndMergeMergeNodes(expansionTrees.scala:625)
	at at.logic.calculi.expansionTrees.merge$.main(expansionTrees.scala:557)
	at at.logic.calculi.expansionTrees.merge$.applyRec$1(expansionTrees.scala:526)
	at at.logic.calculi.expansionTrees.merge$.apply(expansionTrees.scala:538)
	at at.logic.transformations.herbrandExtraction.extractExpansionTrees$.apply(expansionTrees.scala:13)

The proof in question is first-order with equations in it, but does not do equational inference. Do you know what the reason for the failure is?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=265_

**Comment by newca12** [comment]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on May 07, 2014 05:08:26_

It seems as if the trees aren't assembled correctly, i.e. the lower tree isn't actually an atom. I'll look into it.

Do you know if it works in trunk?

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on May 07, 2014 06:38:56_

Oh interesting - the same result in the trunk, although the error message is better readable:

java.lang.IllegalArgumentException: Bug in merge in extractExpansionTrees. By Construction, the trees to be merge should have the same structure, which is violated for:
Atom(=(hole(pigeon1:ι):ι, 0:ι): o)∧Atom(=(hole(pigeon2:ι):ι, 0:ι): o)
Atom((=(hole(pigeon1:ι):ι, 0:ι): o∧=(hole(pigeon2:ι):ι, 0:ι): o))

**Comment by newca12** [comment]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on May 07, 2014 12:43:19_

Fixed in revision 2066 .

I don't know why the type is printed in the output in the branch. Apparently toString() always adds the type and toPrettyString() doesn't, but i don't why toPrettyString() seems to be used in trunk.

**Status:** Fixed
