### ISSUE TITLE
prover9 parsing fails

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#268]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on October 07, 2014 10:48:00_

GAPT fails to parse a prover9 proof.

Steps to reproduce:

tptp_to_ladr \< array_max_index.tptp > p9.in
prover9 \< p9.in > p9.out
./cli.sh

scala> loadProver9Proof("p9.out")
at.logic.calculi.lk.base.LKRuleCreationException: Auxiliary formulas are not contained in the right part of the sequent
  at at.logic.calculi.resolution.robinson.Paramodulation$.apply(robinson.scala:141)
.....

**Attachment:** [array_max_index.tptp](http://code.google.com/p/gapt/issues/detail?id=268)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=268_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on October 07, 2014 03:19:52_

Hi Daniel, this was a bug which surfaced from the new checks on paramodulation. The translation of a flip rule on negative literals cannot be reproduced in one inference but is done now by the following translation:

      s=t :- s=t         :- s=s
      ------------------------- para
             t=s :- t=s                      t=s :-   x C :- D
             -------------------------------------------------- Res
                             t=s :-  x C :- D

Do you know a (modular) way which does not add this tautology to the clause set?

**Status:** Fixed  
**Labels:** -Type- -Component- -Priority- Type-Defect Component-Parsing Priority-Medium

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on October 07, 2014 03:31:19_

Hi Martin,

thank you so much for the quick fix! Is the proof tree you indicate in your comment correct? It seems weird to me (e.g. the last inference has the same conclusion as the right premise).

But I think that I remember that sometimes, one has to add tautology axioms to be able to translate prover9 to LK, so I would not be surprised if this is in fact necessary here. I think it is also unproblematic to add such clauses.

Thank you again!

**Status:** Verified

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on October 07, 2014 04:59:59_

Hi Daniel!

You are right, i had a wrong premise, the pattern should derive t=s :-  from s=t :- . The transform to LK worked in your example, but i didn't check if this the tautology is handled in general. If you encounter any problems, please tell me :)

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on October 17, 2014 04:47:21_

I am re-opening this issue since I discovered a problem parsing the Prover9 proof from the original problem *as an LK proof*. I.e. the following fails


tptp_to_ladr \< array_max_index.tptp > p9.in
prover9 \< p9.in > p9.out
./cli.sh
scala> loadProver9LKProof("p9.out")
at.logic.calculi.lk.LKQuantifierException: Substituting the term v101back into the given formula ((¬<(f2(s(v101), v1), s(v101))∨<(f2(s(v101), v1), v101))∨=(v101, f2(s(v101), v1))) gives (¬<: (ι->(ι->ο))(f2: (ι->(ι->ι))(s(v101), v101), s: (ι->ι)(v101))∨<: (ι->(ι->ο))(f2: (ι->(ι->ι))(s(v101), v101), v101))∨v101 = f2: (ι->(ι->ι))(s(v101), v101) instead of (¬<: (ι->(ι->ο))(f2: (ι->(ι->ι))(s(v101), v1), s: (ι->ι)(v101))∨<: (ι->(ι->ο))(f2: (ι->(ι->ι))(s(v101), v1), v101))∨v101 = f2: (ι->(ι->ι))(s(v101), v1))
  at at.logic.calculi.lk.WeakRuleHelper.getTerms(quantificationRules.scala:473)
...

**Status:** New

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on October 17, 2014 05:34:43_

Just a question: did you try with a cli from before r2214 (the change in the lambda hash function) or afterwards?

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on October 20, 2014 00:47:31_

The bug appears in revisions 2213, 2214, and 2215.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on October 20, 2014 05:21:14_

Thank you, I already investigated but haven't found the cause yet. I'll report back tomorrow.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on October 21, 2014 12:08:58_

The status report so far: it seems thebug is really in substitution. You can reproduce it with the following code (after my next commit):

     val p = loadLLK("array-subproof.llk").proof("THEPROOF") //load proof from file attached to bug report
     val (proof,_) = mapProof(p,hol2folpure.apply) //convert to first order
     val terms = List("v0","f2(s(v101),v1)","v1","v101").map(x => parse.p9term(x, true)) //create the terms for the substitution
     val sub = Substitution(List((terms(0).asInstanceOf[FOLVar], terms(1)), (terms(2).asInstanceOf[FOLVar], terms(3)))) //create the substitution
     prooftool(proof) //show proof in prooftool
     at.logic.algorithms.lk.applySubstitution(proof,sub) //code breaks here

it seems the problem comes from the combination of:
* v0 and v1 occur both free and bound in th eend-sequent
* the substitution is not idempotent
* the quantifier inference is from F[v0] to all v0 F[v0]

i will report later if i have a proper fix. It somehow reminds me of a bug i already fixed(the bound variable needed to be removed from the substitution there).

**Attachment:** [array-subproof.llk bug-268.png](http://code.google.com/p/gapt/issues/detail?id=268#hc8)

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 22, 2014 01:04:50_

For the record:
* a variable occuring both free and bound in a formula (sequent or proof) does not pose a problem for correct handling of substitutions and should not pose a problem for our implementation.
* this subsitution is not idempotent and there is no reason substitutions should be idempotent.
* Having a quantifier inference infer all v0 F[v0] from F[v0] does not pose a problem for correctness and should not pose a problem for our implementation.

The semantics of a substitution is very clear: a substitution is a mapping of variables to terms. Its application to a formula, sequent or proof consists of replacing all _free_ occurrences of the variables in its domain by the respective term. This may require renaming of bound (and only of bound) variables in the formulas.

In particular: the auxiliary formula of the upper forall:left inference of this proof after applying the substitution should be:
(¬<: (ι->(ι->ο))(f2: (ι->(ι->ι))(s(v101), v101), s: (ι->ι)(v101))∨<: (ι->(ι->ο))(f2: (ι->(ι->ι))(s(v101), v101), v101))∨v101 = f2: (ι->(ι->ι))(s(v101), v101)

the main formula of the lower forall:left-inference should not be changed by the substiution as it does not contain any variable from the domain of the substitution free.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on October 22, 2014 04:10:07_

Hi Stefan!

With the substitution { v0 \<- f2(s(v101), v1), v1 \<- v101 } I obtain -(f2(s(v101),v1) \< s(v101)) | (f2(s(v101),v1) \< v101)) | (v101 = f2(s(v101),v1)) as the auxiliary formula for the first forall inference. Perhaps to make things more clear, I attached how I expect the proof to be returned. Would you agree this is correct?

**Attachment:** [bug-268b.png](http://code.google.com/p/gapt/issues/detail?id=268#hc10)

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on October 22, 2014 04:20:48_

To make things a bit more precise, we have the following check implemented:

The arguments to the forall rule are the auxiliary formula A with (possibly multiple) occurrences of the substitution term t in it and a main formula (all x M) we would like to obtain. What happens in the check is the following:

* We create the substitution sigma = { x \<- t }
* We check if sigma applied to M is equal to A

This is fine as long as x does not occur free in A. The binder must introduce a different variable, which does not happen at the moment since the x is manually specified.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 22, 2014 04:25:55_

Yes, I agree that the proof you attach is correct. In fact, it is not necessary (though not harmful either) to rename the bound variable v_0 to y. On the other hand, the inner bound variable v_1 must be renamed, e.g. to x. It was my understanding that this kind of renaming is implemented in the application of a substitution to a lambda expression.

Sorry for the mistake  in `#9` above, I copied that in a hurry without checking it in detail.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 22, 2014 04:31:57_

In response to your `#11`: I agree that having the constructor rename x in case it occurs free in A would be a good fix. An alternative may be to throw an exception in this case and thus make it the responsiblity of the user of the constructor to ensure that this formula (all x M) can actually be created. However, I am rather in favour of doing this within the constructor - it seems the more appropriate place to me.

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 22, 2014 11:09:50_

Fixed by commit 2250.
The problem is explain in the commit message, but I can elaborate here if it is not clear.

**Status:** Fixed  
**Cc:** giselle....@gmail.com
