### ISSUE TITLE
veriT fails to prove deep formula of expansion tree obtained from loadProver9LKProof

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#269]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 09, 2014 16:06:31_

In the CLI, do:

import at.logic.provers.veriT.VeriTProver
import at.logic.calculi.expansionTrees.toDeep
val p = loadProver9LKProof( "integration_tests/misc_test/src/test/resources/ALG138+1.out" )
val seq = toDeep( extractExpansionSequent( p ))
VeriTProver.isValid( seq )

This results in:

(error "smt2_term: unresolved symbol u22A5 on line 32")
java.lang.RuntimeException: Nonzero exit value: 255
  at scala.sys.package$.error(package.scala:27)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
  at at.logic.provers.veriT.VeriTProver$.isValid(VeriTProver.scala:19)
  ... 33 elided

The expected result would be isValid to return true. I am using veriT 201310d.

This is also an integration test (currently skipped) in MiscTest.scala:210.

I am attaching the toProve.smt file.

**Attachment:** [toProve.smt](http://code.google.com/p/gapt/issues/detail?id=269)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=269_

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 10, 2014 06:14:36_

This is because the "toString" method for top and bottom prints the unicode
character for these constants, while verit takes "true" and "false". I will
change this directly in the verit exporting code.

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 10, 2014 06:20:44_

This issue was closed by revision r2183 .

**Status:** Fixed
