### ISSUE TITLE
language incompatibility between prover9 and veriT

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#270]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 10, 2014 15:02:10_

Some symbols that are imported from prover9 are passed to veriT by the gapt system but veriT does not accept them. For example, do the following:

import at.logic.provers.veriT.VeriTProver
import at.logic.calculi.expansionTrees.toDeep
val fn = "../testing/TSTP/prover9/ALG/ALG002-1/Prover9---1109a.UNS-Ref.s.out"
val p = loadProver9LKProof( fn )
val seq = toDeep( extractExpansionSequent( p ))
(new VeriTProver()).isValid( seq )

This results in:
error : syntax error on line 3 : [\]
java.lang.RuntimeException: Nonzero exit value: 1
  at scala.sys.package$.error(package.scala:27)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
  at at.logic.provers.veriT.VeriTProver.isValid(VeriTProver.scala:19)

I am attaching the toProve.smt file generated by this call. The offending line is:
(declare-fun multiplicative\_identity () S)

This happens frequently with prover9-proofs from the TSTP, e.g. also for:
val fn = "../testing/TSTP/prover9/ALG/ALG003-1/Prover9---1109a.UNS-Ref.s.out"
val fn = "../testing/TSTP/prover9/PUZ/PUZ002-1/Prover9---1109a.UNS-Ref.s.out"

I believe that the cleanest solution would be a (input-specific) bijective mapping between internal gapt symbols and symbols acceptable to veriT. This mapping would be applied before sending something to veriT and its inverse would be applied when reading back something from veriT.

**Attachment:** [toProve.smt](http://code.google.com/p/gapt/issues/detail?id=270)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=270_

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 10, 2014 06:13:05_

The problem there is because there is a function named
"multiplicative_inverse" in prover9 and, for some reason, after importing
it into gapt, it becomes "multiplicative\_inverse". I believe this is
because of some latex compatibility issue, but in this case, it should only
be changed when importing/exporting in latex format. If the function name
in the prover9 files is used as is, it works for verit.

I can check prover9's code and see if there is a big overhead on changing
this.

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 10, 2014 07:03:21_

Prover9.parse_prover9 has an implicit parameter called "escape_underscore" which is true by default... This is not exposed to the cli command loadProver9LKProof (it is though exposed to loadProver9Proof). If the command is called with "escape_underscore" = false, veriT works. There are a few solutions for this:

1. Change the cli command so that it calls parsing with escape_underscore = false
2. Change the cli so that this optional parameter is available for loadProver9LKProof
3. Change the implicit parameter to false as the default value

I am for solution 1 or 3. 
If we go for solution 2, I would say to make the parameter explicit. It would be much easier to find the source of this bug (and the fix) if this was the case.

What do you think?

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 10, 2014 07:29:11_

Martin, do you have any thoughts on this? Why do we escape underscores in prover9-import? We can also discuss this in the gapt meeting next week.

**Cc:** Martin.R...@googlemail.com

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 13, 2014 06:01:15_

This issue was closed by revision r2190 .

**Status:** Fixed

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on October 13, 2014 06:49:49_

Sorry, I didn't see the email till today -- the reason for escape underscore is that we assume our symbols to be latex code. If you now import a tptp proof containing e.g. go_west, the prooftool output is unreadable. Since the viewer can not decide how to interpret the symbol, you have to select the option during proof loading. Setting the default to off is fine, I will just add an option to do the escapes for presentation purposes.
