### ISSUE TITLE
NCut-Introduction fails with FlatTermSetException: Term is not a function

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#273]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 17, 2014 11:40:28_

To reproduce, do the following in the CLI:
val p = loadProver9LKProof( "../testing/TSTP/prover9/ALG/ALG011-1/Prover9---1109a.UNS-Ref.s.out" )
val q = ncutIntro( p, 2, at.logic.provers.maxsat.MaxSATSolver.QMaxSAT )

This results in:
DEBUG NCutIntroduction$ -    NCUTINTRO:
DEBUG NCutIntroduction$ -    grammars: List({ tuple1(f(α_2, α_1)),tuple2(α_2, α_1),tuple3(α_1, α_2),tuple5(α_2, α_1, a1),α_1 } o { List(tuple2(a2, a2)),List(tuple3(a1, a1)),List(tuple4(f(a2, a1))),List(tuple5(a2, a2, a1)) }, { tuple5(a2, a2, a1),tuple4(f(a2, a1)),tuple3(a1, a1),tuple2(a2, a2),tuple5(α_2, tuple5(a2, a2, a1), a1),tuple5(α_2, tuple4(f(a2, a1)), a1),tuple5(α_2, tuple3(a1, a1), a1),tuple5(α_2, tuple2(a2, a2), a1),tuple3(tuple5(a2, a2, a1), α_2),tuple3(tuple4(f(a2, a1)), α_2),tuple3(tuple3(a1, a1), α_2),tuple3(tuple2(a2, a2), α_2),tuple2(α_2, tuple5(a2, a2, a1)),tuple2(α_2, tuple4(f(a2, a1))),tuple2(α_2, tuple3(a1, a1)),tuple2(α_2, tuple2(a2, a2)),tuple1(f(α_2, tuple5(a2, a2, a1))),tuple1(f(α_2, tuple4(f(a2, a1)))),tuple1(f(α_2, tuple3(a1, a1))),tuple1(f(α_2, tuple2(a2, a2))) } o {  })
at.logic.algorithms.cutIntroduction.FlatTermSetException: Term is not a function
  at at.logic.algorithms.cutIntroduction.FlatTermSet.getTermTuple(FlatTermSet.scala:57)
  at at.logic.algorithms.cutIntroduction.CutIntroduction$$anonfun$14.apply(CutIntroduction.scala:328)
  at at.logic.algorithms.cutIntroduction.CutIntroduction$$anonfun$14.apply(CutIntroduction.scala:321)
  at scala.collection.immutable.List$$anonfun$foldRight$1.apply(List.scala:399)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
  at scala.collection.immutable.List.foldLeft(List.scala:83)
  at scala.collection.immutable.List.foldRight(List.scala:399)
  at at.logic.algorithms.cutIntroduction.CutIntroduction$.computeCanonicalSolution(CutIntroduction.scala:321)
  at at.logic.algorithms.cutIntroduction.NCutIntroduction$$anonfun$32.apply(CutIntroduction.scala:634)
  at at.logic.algorithms.cutIntroduction.NCutIntroduction$$anonfun$32.apply(CutIntroduction.scala:634)
  at scala.collection.immutable.List.map(List.scala:274)
  at at.logic.algorithms.cutIntroduction.NCutIntroduction$.apply(CutIntroduction.scala:634)
  at at.logic.algorithms.cutIntroduction.NCutIntroduction$.apply(CutIntroduction.scala:580)
  at at.logic.cli.GAPScalaInteractiveShellLibrary.ncutIntro$.apply(GAPScalaInteractiveShellLibrary.scala:721)
  ... 33 elided

But it should compute the canonical solution(s).

_Original issue: http://code.google.com/p/gapt/issues/detail?id=273_

**Comment by newca12** [comment]
_From [christop...@gmail.com](https://code.google.com/u/105962898423732300418/) on October 17, 2014 02:42:38_

I'll take a look on it asap. Thank you!

**Comment by newca12** [comment]
_From [christop...@gmail.com](https://code.google.com/u/105962898423732300418/) on October 17, 2014 05:40:29_

I managed to track down the cause of this issue.

It seems that computeCanonicalSolution has a problem when dealing with grammars where on the right-hand side (i.e. the U in a decomposition) is a non-function term.

I this happens maybe due to the fact, that this was not possible to happen for the old method of cutintroduction, i.e. for 1 cut, since this would lead to a trivial decomposition. When introducing multiple cuts, e.g. following rule can appear in the grammar \alpha_0 \to \alpha_1. Obviously \alpha_1 is not a function term and thus a FlatTermSetException is thrown (either in getTermTuple or getFormula in FlatTermSet.scala).

I did not write this code, therefore I suppose we should discuss this issue with Giselle. To efficiently approach this issue, we should also discuss the computation of one single grammar, i.e. a single canoncial solution, instead of a list of such as it is implemented for now. I hope we can sort things out Mondays, except anyone has another idea to quickfix this issue.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on October 17, 2014 05:43:06_

Yes, let's discuss this on Monday.

**Cc:** fra...@gmail.com

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on October 20, 2014 05:44:51_

Dear all,

I am not sure I'll be able to make it to the meeting today... I will arrive
earlier at the French consulate and see if they are free before 16, but I
just cannot predict what will happen. In any case, I've been investigating
this bug, and here's what happens. For this example, only one cut can be
introduced (according to ncutintro), so both methods find only one grammar.

This is the grammar found by cutIntro(p, ExactBound(1)):

U:  tuple3(f(a2, α_0), a1), tuple1(f(a2, f(α_0, a1))), tuple2(a2, f(α_0,
a1)), tuple5(a2, α_0, a1), tuple4(f(a2, a1)), tuple3(a1, a1), tuple2(a2, a2)
S: List(a1), List(a2)
Size: 7 + 2 = 9

And this is the grammar found by ncutIntro:

U: tuple1(f(a2, f(α_1, a1))), tuple3(α_1, a1), tuple5(a2, α_1, a1),
tuple3(f(a2, α_1), a1), α_1, tuple2(a2, f(α_1, a1))
S: List(tuple2(a2, a2)), List(tuple4(f(a2, a1))), List(a1), List(a2)
Size: 6 + 4 = 10

The exception is thrown because we have the assumption that every term in U
has "tuple..." as the head symbol. As a consequence, no terms in S should
have this head symbol. I don't know the exact procedure of ncutIntro to
find these grammars, but my impression is that there is something wrong
there, as not only there is a variable in U but also there are "tuple"
terms in S *and* the grammar found is bigger than that found by cutIntro.

One interesting observation is that the second grammar does not contain
ground terms in U, and this is a special case for cutIntro (i.e. the
insertion of ground terms in U in order to find smaller grammars). Note
that if the ground "tuple" terms of S are added to U, and the extra alpha_1
is removed, we end up with a grammar of the same size as the first. Should
this be treated as a special case as well of should the ncutIntro algorithm
compute this from the beginning?

Hopefully I'll manage to come to the meeting (a bit late) today to discuss
this.

Best,
Giselle

**Comment by newca12** [comment]
_From [christop...@gmail.com](https://code.google.com/u/105962898423732300418/) on October 20, 2014 13:23:42_

I found the bug that caused this.
I forgot to add propositional Variables for the according production rules near D(q,0,q), i.e. \alpha_0 => q (or x_{0,q}).

**Status:** Fixed
