### ISSUE TITLE
Prover9 parsing fails with new Equational rules

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#276]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on November 28, 2014 18:21:17_

I noticed a lot of prover9's proofs which were previously parsed correctly and that now fail with an exception on the equational rules.
For example:

scala> loadProver9LKProof("../testing/TSTP/prover9/COL/COL091-1/Prover9---1109a.UNS-Ref.s.out")
at.logic.calculi.lk.base.LKRuleCreationException: Term comb_app(comb_app(combS, ap_contractE_sk1p(v0, v1, v2)), ap_contractE_sk1q(v0, v1, v2)) not found in formula =(v0, v0).
  at at.logic.calculi.lk.EquationRight2Rule$.apply(equationalRules.scala:767)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:151)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:121)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:157)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:116)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:115)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:115)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:115)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:121)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:116)
  at at.logic.algorithms.resolution.RobinsonToLK$.apply(robinson.scala:37)
  at at.logic.cli.GAPScalaInteractiveShellLibrary.Robinson2LK$.apply(GAPScalaInteractiveShellLibrary.scala:997)
  at at.logic.cli.GAPScalaInteractiveShellLibrary.loadProver9LKProof$.apply(GAPScalaInteractiveShellLibrary.scala:209)
  ... 33 elided

_Original issue: http://code.google.com/p/gapt/issues/detail?id=276_

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on November 28, 2014 09:21:37_

**Owner:** giselle....@gmail.com

**Comment by newca12** [comment]
_From [sziv...@gmail.com](https://code.google.com/u/107462141115948183633/) on November 28, 2014 12:55:43_

I'll try modifying the parsing algorithm to use macro rules. If that doesn't help, something is seriously wrong and I'll have to think of something else.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on November 28, 2014 23:13:59_

adding Martin in CC as he is the author of the prover9-import.

**Cc:** Martin.R...@googlemail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on November 29, 2014 04:55:01_

Hi, I don't think macro rules change anything, since the infereces were checked before as single paramodulations. I would guess that either

* the left hand-side and right-hand side of a paramodulation inference is swapped (perhaps when the prior flipped equality detection code was replaced by the new rules, some arguments changed?)

* a subsitution was not applied

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on December 04, 2014 02:00:38_

Fixed on r2355 .

Thank you!! :)

**Status:** Fixed
