### ISSUE TITLE
Compiling Error...

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#39]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on November 15, 2009 18:58:59_

I just did an update, tried to compile and got the following error message:

Compiling 6 source files to 
C:\Users\Bruno\Documents\NetBeansProjects\GAPT\trunk\source\utils\target\cl
asses
java.lang.ClassNotFoundException: scala.tools.nsc.Main
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:276)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
        at 
org.scala_tools.maven.executions.MainHelper.runMain(MainHelper.java:141)
        at 
org.scala_tools.maven.executions.MainWithArgsInFile.main(MainWithArgsInFile
.java:26)
\------------------------------------------------------------------------
Reactor Summary:
\------------------------------------------------------------------------
General Architecture for Proofs ....................... SUCCESS [1.904s]
General utilities ..................................... FAILED [1.697s]
Syntax definitions .................................... NOT BUILT
Algorithms ............................................ NOT BUILT
Unification algorithms ................................ NOT BUILT
Theorem Provers ....................................... NOT BUILT
Resolution Automated Theorem Prover ................... NOT BUILT
Proof Transformations ................................. NOT BUILT
Cut Elimination by RESolution ......................... NOT BUILT
Gentzen's Cut-Elimination ............................. NOT BUILT
Skolemization Transformations ......................... NOT BUILT
Graphical User Interfaces ............................. NOT BUILT
Proof Tool ............................................ NOT BUILT
Tools for parsing ..................................... NOT BUILT
\------------------------------------------------------------------------
[ERROR]The following mojo encountered an error while executing:
[ERROR]Group-Id: org.scala-tools
[ERROR]Artifact-Id: maven-scala-plugin
[ERROR]Version: 2.12.2
[ERROR]Mojo: compile
[ERROR]brought in via: POM
[ERROR]While building project:
[ERROR]Group-Id: at.logic
[ERROR]Artifact-Id: utils
[ERROR]Version: 1.0-SNAPSHOT
[ERROR]From file: 
C:\Users\Bruno\Documents\NetBeansProjects\GAPT\trunk\source\utils\pom.xml
[ERROR]Reason: wrap: org.apache.commons.exec.ExecuteException: Process 
exited with an error: -2147483648(Exit value: -2147483648)
\------------------------------------------------------------------------
For more information, run with the -e flag
\------------------------------------------------------------------------
BUILD FAILED
\------------------------------------------------------------------------
Total time: 6 seconds
Finished at: Sun Nov 15 18:53:15 CET 2009
Final Memory: 65M/152M
\------------------------------------------------------------------------

_Original issue: http://code.google.com/p/gapt/issues/detail?id=39_

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 15, 2009 10:43:08_

I dont get the error. Did you try to clean the files and then compile? Anyway, nothing has changed in the 
pom.xml file in the last few weeks.

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on November 15, 2009 11:28:02_

First I did a "build" and it didn't work... Then I tried a "clean and build" and it 
also didn't work... it's the same problem in both cases...

I have the impression that whenever there are big changes in the code (I hadn't updated 
since one week before my thesis defense), Maven/NetBeans/Subversion does not behave 
very well... I don't know why...

I made an update in the whole project that contains all other subprojects...

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on November 15, 2009 11:39:54_

I have just deleted my local version completely. Then I did a "checkout" of the whole 
project once again. I tried to build it, and I got the same error message as before. 
(The whole error message is attached below).

Perhaps it is something related to Maven trying to resolve versions of the Scala 
plugin...



WARNING: You are running embedded Maven builds, some build may fail due to 
incompatibilities with latest Maven release.
         To set Maven instance to use for building, click here.
Scanning for projects...
Reactor build order: 
  General Architecture for Proofs
  General utilities
  Syntax definitions
  Algorithms
  Unification algorithms
  Theorem Provers
  Resolution Automated Theorem Prover
  Proof Transformations
  Cut Elimination by RESolution
  Gentzen's Cut-Elimination
  Skolemization Transformations
  Graphical User Interfaces
  Proof Tool
  Tools for parsing
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
Attempting to resolve a version for plugin: org.scala-tools:maven-scala-plugin using 
meta-version: LATEST
Using version: 2.12.2 of plugin: org.scala-tools:maven-scala-plugin
[#compile]
[scala:compile]
Checking for multiple versions of scala
includes = [**/*.scala,**/*.java,]
excludes = []
[WARN]No source files found.
[#test-compile]
[scala:testCompile]
Checking for multiple versions of scala
includes = [**/*.scala,**/*.java,]
excludes = []
[WARN]No source files found.
[#package]
[site:attach-descriptor]
[#install]
[install:install]
Installing C:\Users\Bruno\Documents\NetBeansProjects\GAP2\trunk\source\pom.xml to 
C:\Users\Bruno\.m2\repository\at\logic\gap\1.0-SNAPSHOT\gap-1.0-SNAPSHOT.pom
[#process-resources]
[resources:resources]
Using default encoding to copy filtered resources.
[#compile]
[compiler:compile]
Nothing to compile - all classes are up to date
[scala:compile]
Checking for multiple versions of scala
includes = [**/*.scala,**/*.java,]
excludes = []
Compiling 6 source files to 
C:\Users\Bruno\Documents\NetBeansProjects\GAP2\trunk\source\utils\target\classes
java.lang.ClassNotFoundException: scala.tools.nsc.Main
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:276)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
        at org.scala_tools.maven.executions.MainHelper.runMain(MainHelper.java:141)
        at 
org.scala_tools.maven.executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
\------------------------------------------------------------------------
Reactor Summary:
\------------------------------------------------------------------------
General Architecture for Proofs ....................... SUCCESS [1.506s]
General utilities ..................................... FAILED [1.785s]
Syntax definitions .................................... NOT BUILT
Algorithms ............................................ NOT BUILT
Unification algorithms ................................ NOT BUILT
Theorem Provers ....................................... NOT BUILT
Resolution Automated Theorem Prover ................... NOT BUILT
Proof Transformations ................................. NOT BUILT
Cut Elimination by RESolution ......................... NOT BUILT
Gentzen's Cut-Elimination ............................. NOT BUILT
Skolemization Transformations ......................... NOT BUILT
Graphical User Interfaces ............................. NOT BUILT
Proof Tool ............................................ NOT BUILT
Tools for parsing ..................................... NOT BUILT
\------------------------------------------------------------------------
[ERROR]The following mojo encountered an error while executing:
[ERROR]Group-Id: org.scala-tools
[ERROR]Artifact-Id: maven-scala-plugin
[ERROR]Version: 2.12.2
[ERROR]Mojo: compile
[ERROR]brought in via: POM
[ERROR]While building project:
[ERROR]Group-Id: at.logic
[ERROR]Artifact-Id: utils
[ERROR]Version: 1.0-SNAPSHOT
[ERROR]From file: 
C:\Users\Bruno\Documents\NetBeansProjects\GAP2\trunk\source\utils\pom.xml
[ERROR]Reason: wrap: org.apache.commons.exec.ExecuteException: Process exited with an 
error: -2147483648(Exit value: -2147483648)
\------------------------------------------------------------------------
For more information, run with the -e flag
\------------------------------------------------------------------------
BUILD FAILED
--------------------------------------...

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on November 15, 2009 11:39:54_

...----------------------------------
Total time: 6 seconds
Finished at: Sun Nov 15 20:34:23 CET 2009
Final Memory: 72M/152M
\------------------------------------------------------------------------

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on November 15, 2009 23:55:39_

I have downloaded the most recent version of Maven (2.2.1) and configured NetBeans to 
use this version, instead of using its own internal maven. In this way, the warning 
message does not appear anymore.

But the problem still happens.

Here is the new error message: (too big... I will send by email...)

**Status:** Started

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on November 16, 2009 00:35:04_

I cannot reproduce the error. Fresh checkout and my old working copy both work on my
Ubuntu.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 16, 2009 00:46:51_

for windows users only: http://groups.google.com/group/maven-and-scala/browse_thread/thread/14758957ddcf118b

**Status:** Fixed

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 18, 2011 08:57:26_

These issues are so old that I will assume that they have been already verified, even though their status still says otherwise...

In the future, remember: when you finish an issue, set its status to "fixed". From time to time, I will check the list of fixed issues, to verify that they are indeed fixed...

**Status:** Verified
