### ISSUE TITLE
AndLeftRule test fails

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#93]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 04, 2010 00:56:36_

testing LK: the LKTest fails to compile due to missing AndLeftRule. Adding the macro package makes the test compiles but then it fails on the AndLeftRule test:

The factories/extractors for LK should work for AndLeftRule  Time elapsed: 0.004 sec  \<<< ERROR!
org.specs.runner.UserError: at.logic.calculi.lk.base.LKRuleCreationException: Formulas to be contracted are of the same occurrence
        at at.logic.calculi.lk.propositionalRules.ContractionLeftRule$.apply(propositionalRules.scala:137)
        at at.logic.calculi.lk.macroRules.AndLeftRule$.apply(macroRules.scala:23)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=93_

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 04, 2010 00:04:56_

Fixed in revision 527 .

**Status:** Fixed

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 18, 2011 08:57:27_

These issues are so old that I will assume that they have been already verified, even though their status still says otherwise...

In the future, remember: when you finish an issue, set its status to "fixed". From time to time, I will check the list of fixed issues, to verify that they are indeed fixed...

**Status:** Verified
