### ISSUE TITLE
FOLUnificationAlgorithm fails 

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#97]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 27, 2010 14:52:11_

scala.MatchError: =(∩(x_{7}, x_{6}), ∩(x_{6}, x_{7}))
	at at.logic.algorithms.unification.fol.FOL

trying to unify the following exception is being raised, probably because we try to unify two formulas and not two terms, but unification of formulas should be allowed (i.e. a=x should be unified with y=b for example)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=97_

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 27, 2010 07:30:54_

I added unification of formulas in revision 571 . Perhaps it is a problem with my code, not Cvetan's?

**Cc:** shaolintl

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 04:08:12_

sorry for not putting enough details:

scala.MatchError: =(∩(x_{7}, x_{6}), ∩(x_{6}, x_{7}))
	at at.logic.algorithms.unification.fol.FOLUnificationAlgorithm$.getVars(FOLUnificationAlgorithm.scala:42)
	at at.logic.algorithms.unification.fol.FOLUnificationAlgorithm$.gd5$1(FOLUnificationAlgorithm.scala:61)
	at at.logic.algorithms.unification.fol.FOLUnificationAlgorithm$.unifySetOfTuples(FOLUnificationAlgorithm.scala:48)
	at at.logic.algorithms.unification.fol.FOLUnificationAlgorithm$.unify(FOLUnificationAlgorithm.scala:24)
	at at.logic.algorithms.unification.fol.FOLUnificationAlgorithm$.unify(FOLUnificationAlgorithm.scala:16)

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on January 04, 2011 04:12:28_

Changed code in revision 575 , should work now.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 04:19:42_

yes, now it fails in some other place in my code..

**Status:** Fixed

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 25, 2011 22:36:02_

**Status:** Verified
