### ISSUE TITLE
Paramodulation generates illegal terms

### ISSUE THREAD

**Issue by newca12** [newca12/gapt#99]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 13:18:52_

when running automatic robinson atp on the lattice proof:

import at.logic.cli.GAPScalaInteractiveShellLibrary._
import at.logic.language.fol._ 
val proof = loadProofs("/marvin/shaolin/Projects/integration_tests/lattice_test/src/test/resources/lattice-in.xml.gz").head._2
val struct = extractStruct(proof)
val cl = structToClausesList(struct)
val cl2 = cl.map(x => at.logic.calculi.resolution.robinson.Clause(x.getSequent.antecedent.map(y => FOLFormula(y)), x.getSequent.succedent.map(y => FOLFormula(y))))
val res = refuteFOL(cl2)

we get:
java.lang.ClassCastException: at.logic.language.fol.FOLFactory$$anon$3 cannot be cast to at.logic.language.fol.FOLFormula
	at at.logic.provers.atp.commands.robinson.ParamodulationCommand$$anonfun$apply$7$$anonfun$apply$8$$anonfun$apply$9.apply(robinson.scala:124)
	at at.logic.provers.atp.commands.robinson.ParamodulationCommand$$anonfun$apply$7$$anonfun$apply$8$$anonfun$apply$9.apply(robinson.scala:110)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
	at scala.collection.immutable.List.foreach(List.scala:45)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=99_

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 09:56:57_

The error is due to the fact that first order unification unify a first order variable of type i with a formula of type o (in paramodulation it is assumed to fail)

**Blockedon:** 101

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 04, 2011 10:31:39_

i do another check of types in paramodulation

**Status:** Fixed

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 18, 2011 08:57:27_

These issues are so old that I will assume that they have been already verified, even though their status still says otherwise...

In the future, remember: when you finish an issue, set its status to "fixed". From time to time, I will check the list of fixed issues, to verify that they are indeed fixed...

**Status:** Verified
